/* Copyright 2025 predic8 GmbH, www.predic8.com

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License. */

package com.predic8.membrane.annot.util;

import com.predic8.membrane.annot.Grammar;
import com.predic8.membrane.annot.yaml.*;
import org.jetbrains.annotations.*;

import java.io.IOException;
import java.lang.reflect.InvocationTargetException;
import java.util.concurrent.CountDownLatch;

import static java.util.Objects.requireNonNull;

public class YamlParser {

    public static final String AUTOGENERATED_GRAMMER_CLASSNAME = "com.predic8.membrane.demo.config.spring.GrammarAutoGenerated";

    public YamlParser(String resourceName) throws ClassNotFoundException, NoSuchMethodException, InvocationTargetException, InstantiationException, IllegalAccessException, IOException, InterruptedException, YamlSchemaValidationException {
        Grammar generator = getGrammar();

        CountDownLatch cdl = new CountDownLatch(1);

        BeanRegistry beanRegistry = new BeanRegistryImplementation(getLatchObserver(cdl),generator);
        beanRegistry.registerBeanDefinitions(GenericYamlParser.parseMembraneResources(
                requireNonNull(getClass().getResourceAsStream(resourceName)), generator));

        cdl.await();
    }

    private @NotNull Grammar getGrammar() throws InstantiationException, IllegalAccessException, InvocationTargetException, NoSuchMethodException, ClassNotFoundException {
        return (Grammar) getClass().getClassLoader()
                .loadClass(AUTOGENERATED_GRAMMER_CLASSNAME)
                .getConstructor()
                .newInstance();
    }

    /**
     * Used to get notification about termination of parsing
     */
    private static @NotNull BeanCacheObserver getLatchObserver(CountDownLatch cdl) {
        return new BeanCacheObserver() {
            @Override
            public void handleAsynchronousInitializationResult(boolean empty) {
                cdl.countDown();
            }

            @Override
            public void handleBeanEvent(BeanDefinition bd, Object bean, Object oldBean) {

            }

            @Override
            public boolean isActivatable(BeanDefinition bd) {
                return true;
            }
        };
    };
}
