package com.predic8.membrane.annot.util;

import com.predic8.membrane.annot.K8sHelperGenerator;
import com.predic8.membrane.annot.yaml.BeanRegistry;
import com.predic8.membrane.annot.yaml.GenericYamlParser;
import org.yaml.snakeyaml.Yaml;

import java.io.IOException;
import java.io.InputStreamReader;
import java.lang.reflect.InvocationTargetException;

import static java.util.Objects.requireNonNull;

public class YamlParser {
    private final BeanRegistry beanRegistry;

    public YamlParser(String resourceName) throws ClassNotFoundException, NoSuchMethodException, InvocationTargetException, InstantiationException, IllegalAccessException, IOException {
        K8sHelperGenerator generator = (K8sHelperGenerator) getClass().getClassLoader()
                .loadClass("com.predic8.membrane.demo.config.spring.K8sHelperGeneratorAutoGenerated")
                .getConstructor()
                .newInstance();

        beanRegistry = GenericYamlParser.parseMembraneResources(getClass().getResourceAsStream(resourceName), generator);

    }

    public BeanRegistry getBeanRegistry() {
        return beanRegistry;
    }
}
