package com.predic8.membrane.annot.util;

import com.predic8.membrane.annot.K8sHelperGenerator;
import com.predic8.membrane.annot.yaml.GenericYamlParser;
import tools.jackson.databind.ObjectMapper;
import tools.jackson.dataformat.yaml.YAMLFactory;

import java.io.IOException;
import java.io.InputStreamReader;
import java.lang.reflect.InvocationTargetException;
import java.util.Iterator;

import static java.util.Objects.requireNonNull;

public class YamlParser {
    private final Object result;

    public YamlParser(String resourceName) throws ClassNotFoundException, NoSuchMethodException, InvocationTargetException, InstantiationException, IllegalAccessException, IOException {
        K8sHelperGenerator generator = (K8sHelperGenerator) getClass().getClassLoader()
                .loadClass("com.predic8.membrane.demo.config.spring.K8sHelperGeneratorAutoGenerated")
                .getConstructor()
                .newInstance();

        try (InputStreamReader reader = new InputStreamReader(
                requireNonNull(getClass().getResourceAsStream(resourceName)),
                java.nio.charset.StandardCharsets.UTF_8)) {
            this.result = GenericYamlParser.parseMembraneObject(
                    new ObjectMapper(new YAMLFactory()).readerFor(Object.class).readValues(reader),
                    generator,
                    null);
        }
    }

    public Object getResult() {
        return result;
    }
}
