# Branch depending on scopes
#    See demo-keys.txt
GET / HTTP/1.1
Host: localhost:3000
X-Key: 123456789
###

GET / HTTP/1.1
Host: localhost:3000
X-Key: key_321_abc
###

# Access will fail, no valid API key provided
GET / HTTP/1.1
Host: localhost:3000
