package com.predic8.membrane.core.interceptor.mcp;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;
import com.predic8.membrane.annot.beanregistry.BeanRegistryImplementation;
import com.predic8.membrane.annot.yaml.ParsingContext;
import com.predic8.membrane.annot.yaml.parsing.GenericYamlParser;
import com.predic8.membrane.core.config.spring.GrammarAutoGenerated;
import com.predic8.membrane.core.exchange.Exchange;
import com.predic8.membrane.core.http.Request;
import com.predic8.membrane.core.interceptor.Outcome;
import com.predic8.membrane.core.router.DefaultRouter;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;

import java.util.stream.Stream;

import static com.predic8.membrane.core.http.MimeType.APPLICATION_JSON;
import static com.predic8.membrane.core.http.MimeType.TEXT_PLAIN;
import static com.predic8.membrane.core.http.Request.METHOD_GET;
import static com.predic8.membrane.core.http.Request.METHOD_POST;
import static com.predic8.membrane.core.interceptor.Outcome.CONTINUE;
import static com.predic8.membrane.core.interceptor.Outcome.RETURN;
import static com.predic8.membrane.core.jsonrpc.JSONRPCResponse.*;
import static org.junit.jupiter.api.Assertions.*;

class MCPProtectionInterceptorTest {

    private static final ObjectMapper OM = new ObjectMapper();
    private static final ObjectMapper YAML = new ObjectMapper(new YAMLFactory());

    @ParameterizedTest(name = "{0}")
    @MethodSource("requestCases")
    void validatesRequests(RequestCase testCase) throws Exception {
        var exc = exchange(testCase.httpMethod(), testCase.contentType(), testCase.body());

        assertEquals(testCase.expectedOutcome(), interceptor(testCase.config()).handleRequest(exc));

        if (testCase.expectedOutcome() == CONTINUE) {
            assertNull(exc.getResponse());
            return;
        }

        assertError(
                exc,
                testCase.expectedStatus(),
                testCase.expectedCode(),
                testCase.expectedMessage(),
                testCase.expectedId()
        );
        if (testCase.expectedStatus() == 405) {
            assertEquals(METHOD_POST, exc.getResponse().getHeader().getFirstValue("Allow"));
        }
    }

    private static Stream<RequestCase> requestCases() {
        String toolsEnabled = """
                methods:
                  toolsList: true
                  toolsCall: true
                  notifications: true
                tools:
                  - allow: '^(listProxies|getStatistics|getExchanges)$'
                  - deny: '.*'
                """;

        String toolsCallEnabled = """
                methods:
                  toolsCall: true
                """;

        return Stream.of(
                continues(
                        "initialize is always allowed",
                        "",
                        """
                        {"jsonrpc":"2.0","id":1,"method":"initialize","params":{}}
                        """
                ),
                continues(
                        "ping is always allowed",
                        "",
                        """
                        {"jsonrpc":"2.0","id":2,"method":"ping","params":{}}
                        """
                ),
                continues(
                        "enabled tools list is allowed",
                        toolsEnabled,
                        """
                        {"jsonrpc":"2.0","id":3,"method":"tools/list","params":{}}
                        """
                ),
                rejects(
                        "unsupported MCP methods are always denied",
                        toolsEnabled,
                        """
                        {"jsonrpc":"2.0","id":6,"method":"resources/read","params":{}}
                        """,
                        403,
                        ERR_METHOD_NOT_FOUND,
                        "MCP method 'resources/read' is not allowed.",
                        6
                ),
                continues(
                        "allowed tool call",
                        toolsEnabled,
                        """
                        {"jsonrpc":"2.0","id":7,"method":"tools/call","params":{"name":"getStatistics","arguments":{}}}
                        """
                ),
                rejects(
                        "denied tool call",
                        toolsEnabled,
                        """
                        {"jsonrpc":"2.0","id":8,"method":"tools/call","params":{"name":"deleteEverything","arguments":{}}}
                        """,
                        403,
                        ERR_INVALID_PARAMS,
                        "MCP tool 'deleteEverything' is not allowed.",
                        8
                ),
                continues(
                        "first matching tool rule wins",
                        """
                        methods:
                          toolsCall: true
                        tools:
                          - allow: '^admin\\.status$'
                          - deny: '^admin\\..*$'
                        """,
                        """
                        {"jsonrpc":"2.0","id":9,"method":"tools/call","params":{"name":"admin.status"}}
                        """
                ),
                rejects(
                        "tools call requires named params",
                        toolsCallEnabled,
                        """
                        {"jsonrpc":"2.0","id":10,"method":"tools/call","params":[]}
                        """,
                        400,
                        ERR_INVALID_PARAMS,
                        "requires a params object",
                        10
                ),
                rejects(
                        "tools call requires a tool name",
                        toolsCallEnabled,
                        """
                        {"jsonrpc":"2.0","id":11,"method":"tools/call","params":{"arguments":{}}}
                        """,
                        400,
                        ERR_INVALID_PARAMS,
                        "'name' must be a non-empty string",
                        11
                ),
                rejects(
                        "batch requests are rejected",
                        "",
                        """
                        [{"jsonrpc":"2.0","id":1,"method":"ping"}]
                        """,
                        400,
                        ERR_INVALID_REQUEST,
                        "does not support JSON-RPC batch requests",
                        null
                ),
                rejects(
                        "invalid JSON is rejected",
                        "",
                        "not-json",
                        400,
                        ERR_PARSE_ERROR,
                        "Invalid JSON payload.",
                        null
                ),
                rejects(
                        "invalid JSON-RPC structure is rejected",
                        "",
                        """
                        {"jsonrpc":"2.0","id":12}
                        """,
                        400,
                        ERR_INVALID_REQUEST,
                        "'method' must be a string",
                        null
                ),
                rejects(
                        "blank request bodies are rejected",
                        "",
                        " ",
                        400,
                        ERR_INVALID_REQUEST,
                        "must not be empty",
                        null
                ),
                rejects(
                        "non-JSON content types are rejected",
                        "",
                        METHOD_POST,
                        TEXT_PLAIN,
                        "{}",
                        415,
                        ERR_INVALID_REQUEST,
                        "Expected application/json",
                        null
                ),
                rejects(
                        "non-POST requests are rejected",
                        "",
                        METHOD_GET,
                        APPLICATION_JSON,
                        null,
                        405,
                        ERR_INVALID_REQUEST,
                        "Expected POST",
                        null
                )
        );
    }

    private static RequestCase continues(String name, String config, String body) {
        return new RequestCase(name, config, METHOD_POST, APPLICATION_JSON, body, CONTINUE, null, null, null, null);
    }

    private static RequestCase rejects(String name,
                                       String config,
                                       String body,
                                       int status,
                                       int code,
                                       String message,
                                       Object id) {
        return rejects(name, config, METHOD_POST, APPLICATION_JSON, body, status, code, message, id);
    }

    private static RequestCase rejects(String name,
                                       String config,
                                       String httpMethod,
                                       String contentType,
                                       String body,
                                       int status,
                                       int code,
                                       String message,
                                       Object id) {
        return new RequestCase(name, config, httpMethod, contentType, body, RETURN, status, code, message, id);
    }

    private MCPProtectionInterceptor interceptor(String config) throws Exception {
        MCPProtectionInterceptor interceptor = parseInterceptor(config);
        interceptor.init(new DefaultRouter());
        return interceptor;
    }

    private MCPProtectionInterceptor parseInterceptor(String config) throws Exception {
        JsonNode node = YAML.readTree(wrapConfig(config));
        var grammar = new GrammarAutoGenerated();
        var registry = new BeanRegistryImplementation(grammar);
        return GenericYamlParser.createAndPopulateNode(
                new ParsingContext<>("mcpProtection", registry, grammar, node, "$.mcpProtection", null),
                MCPProtectionInterceptor.class,
                node.get("mcpProtection")
        );
    }

    private String wrapConfig(String config) {
        if (config == null || config.isBlank()) {
            return "mcpProtection: {}\n";
        }
        return "mcpProtection:\n" + config.stripIndent().indent(2);
    }

    private Exchange exchange(String method, String contentType, String body) {
        Request.Builder builder = new Request.Builder()
                .method(method)
                .uri("/");
        if (contentType != null) {
            builder.contentType(contentType);
        }
        if (body != null) {
            builder.body(body);
        }
        return builder.buildExchange();
    }

    private void assertError(Exchange exc, int status, int code, String message, Object id) throws Exception {
        assertNotNull(exc.getResponse());
        assertEquals(status, exc.getResponse().getStatusCode());
        assertEquals(APPLICATION_JSON, exc.getResponse().getHeader().getContentType());

        JsonNode response = OM.readTree(exc.getResponse().getBodyAsStringDecoded());
        assertEquals("2.0", response.path("jsonrpc").asText());
        assertEquals(code, response.path("error").path("code").asInt());
        assertTrue(response.path("error").path("message").asText().contains(message));

        if (id == null) {
            assertTrue(response.path("id").isNull());
        } else {
            assertEquals(OM.valueToTree(id), response.path("id"));
        }
    }

    private record RequestCase(
            String name,
            String config,
            String httpMethod,
            String contentType,
            String body,
            Outcome expectedOutcome,
            Integer expectedStatus,
            Integer expectedCode,
            String expectedMessage,
            Object expectedId
    ) {
        @Override
        public String toString() {
            return name;
        }
    }
}
