/* Copyright 2026 predic8 GmbH, www.predic8.com

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License. */

package com.predic8.membrane.core.interceptor.mcp;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;
import com.predic8.membrane.annot.beanregistry.BeanRegistryImplementation;
import com.predic8.membrane.annot.yaml.ParsingContext;
import com.predic8.membrane.annot.yaml.parsing.GenericYamlParser;
import com.predic8.membrane.core.config.spring.GrammarAutoGenerated;
import com.predic8.membrane.core.exchange.Exchange;
import com.predic8.membrane.core.http.Response;
import com.predic8.membrane.core.http.Request;
import com.predic8.membrane.core.interceptor.Outcome;
import com.predic8.membrane.core.router.DefaultRouter;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Stream;

import static com.predic8.membrane.core.http.MimeType.APPLICATION_JSON;
import static com.predic8.membrane.core.http.MimeType.TEXT_PLAIN;
import static com.predic8.membrane.core.http.Request.METHOD_GET;
import static com.predic8.membrane.core.http.Request.METHOD_POST;
import static com.predic8.membrane.core.interceptor.Outcome.CONTINUE;
import static com.predic8.membrane.core.interceptor.Outcome.RETURN;
import static com.predic8.membrane.core.jsonrpc.JSONRPCResponse.*;
import static org.junit.jupiter.api.Assertions.*;

class MCPProtectionInterceptorTest {

    private static final ObjectMapper OM = new ObjectMapper();
    private static final ObjectMapper YAML = new ObjectMapper(new YAMLFactory());

    @ParameterizedTest(name = "{0}")
    @MethodSource("requestCases")
    void validatesRequests(RequestCase testCase) throws Exception {
        var exc = exchange(testCase.httpMethod(), testCase.contentType(), testCase.body());

        assertEquals(testCase.expectedOutcome(), interceptor(testCase.config()).handleRequest(exc));

        if (testCase.expectedOutcome() == CONTINUE) {
            assertNull(exc.getResponse());
            return;
        }

        assertError(
                exc,
                testCase.expectedStatus(),
                testCase.expectedCode(),
                testCase.expectedMessage(),
                testCase.expectedId()
        );
        if (testCase.expectedStatus() == 405) {
            assertEquals(METHOD_POST, exc.getResponse().getHeader().getFirstValue("Allow"));
        }
    }

    private static Stream<RequestCase> requestCases() {
        String toolsEnabled = """
                methods:
                  toolsList: true
                  toolsCall: true
                  notifications: true
                tools:
                  - allow: '^(listProxies|getStatistics|getExchanges)$'
                  - deny: '.*'
                """;

        String toolsCallEnabled = """
                methods:
                  toolsCall: true
                """;

        return Stream.of(
                continues(
                        "initialize is always allowed",
                        "",
                        """
                                {"jsonrpc":"2.0","id":1,"method":"initialize","params":{}}
                                """
                ),
                continues(
                        "ping is always allowed",
                        "",
                        """
                                {"jsonrpc":"2.0","id":2,"method":"ping","params":{}}
                                """
                ),
                continues(
                        "enabled tools list is allowed",
                        toolsEnabled,
                        """
                                {"jsonrpc":"2.0","id":3,"method":"tools/list","params":{}}
                                """
                ),
                rejects(
                        "unsupported MCP methods are always denied",
                        toolsEnabled,
                        """
                                {"jsonrpc":"2.0","id":6,"method":"resources/read","params":{}}
                                """,
                        403,
                        ERR_METHOD_NOT_FOUND,
                        "MCP method 'resources/read' is not allowed.",
                        6
                ),
                continues(
                        "allowed tool call",
                        toolsEnabled,
                        """
                                {"jsonrpc":"2.0","id":7,"method":"tools/call","params":{"name":"getStatistics","arguments":{}}}
                                """
                ),
                rejects(
                        "denied tool call",
                        toolsEnabled,
                        """
                                {"jsonrpc":"2.0","id":8,"method":"tools/call","params":{"name":"deleteEverything","arguments":{}}}
                                """,
                        403,
                        ERR_INVALID_PARAMS,
                        "MCP tool 'deleteEverything' is not allowed.",
                        8
                ),
                continues(
                        "first matching tool rule wins",
                        """
                                methods:
                                  toolsCall: true
                                tools:
                                  - allow: '^admin\\.status$'
                                  - deny: '^admin\\..*$'
                                """,
                        """
                                {"jsonrpc":"2.0","id":9,"method":"tools/call","params":{"name":"admin.status"}}
                                """
                ),
                rejects(
                        "tools call requires named params",
                        toolsCallEnabled,
                        """
                                {"jsonrpc":"2.0","id":10,"method":"tools/call","params":[]}
                                """,
                        400,
                        ERR_INVALID_PARAMS,
                        "requires a params object",
                        10
                ),
                rejects(
                        "tools call requires a tool name",
                        toolsCallEnabled,
                        """
                                {"jsonrpc":"2.0","id":11,"method":"tools/call","params":{"arguments":{}}}
                                """,
                        400,
                        ERR_INVALID_PARAMS,
                        "'name' must be a non-empty string",
                        11
                ),
                rejects(
                        "batch requests are rejected",
                        "",
                        """
                                [{"jsonrpc":"2.0","id":1,"method":"ping"}]
                                """,
                        400,
                        ERR_INVALID_REQUEST,
                        "does not support JSON-RPC batch requests",
                        null
                ),
                rejects(
                        "invalid JSON is rejected",
                        "",
                        "not-json",
                        400,
                        ERR_PARSE_ERROR,
                        "Invalid JSON payload.",
                        null
                ),
                rejects(
                        "invalid JSON-RPC structure is rejected",
                        "",
                        """
                                {"jsonrpc":"2.0","id":12}
                                """,
                        400,
                        ERR_INVALID_REQUEST,
                        "'method' must be a string",
                        null
                ),
                rejects(
                        "blank request bodies are rejected",
                        "",
                        " ",
                        400,
                        ERR_INVALID_REQUEST,
                        "must not be empty",
                        null
                ),
                rejects(
                        "non-JSON content types are rejected",
                        "",
                        METHOD_POST,
                        TEXT_PLAIN,
                        "{}",
                        415,
                        ERR_INVALID_REQUEST,
                        "Expected application/json",
                        null
                ),
                rejects(
                        "non-POST requests are rejected",
                        "",
                        METHOD_GET,
                        APPLICATION_JSON,
                        null,
                        405,
                        ERR_INVALID_REQUEST,
                        "Expected POST",
                        null
                )
        );
    }

    private static RequestCase continues(String name, String config, String body) {
        return new RequestCase(name, config, METHOD_POST, APPLICATION_JSON, body, CONTINUE, null, null, null, null);
    }

    private static RequestCase rejects(String name,
                                       String config,
                                       String body,
                                       int status,
                                       int code,
                                       String message,
                                       Object id) {
        return rejects(name, config, METHOD_POST, APPLICATION_JSON, body, status, code, message, id);
    }

    private static RequestCase rejects(String name,
                                       String config,
                                       String httpMethod,
                                       String contentType,
                                       String body,
                                       int status,
                                       int code,
                                       String message,
                                       Object id) {
        return new RequestCase(name, config, httpMethod, contentType, body, RETURN, status, code, message, id);
    }

    private MCPProtectionInterceptor interceptor(String config) throws Exception {
        MCPProtectionInterceptor interceptor = parseInterceptor(config);
        interceptor.init(new DefaultRouter());
        return interceptor;
    }

    private MCPProtectionInterceptor parseInterceptor(String config) throws Exception {
        JsonNode node = YAML.readTree(wrapConfig(config));
        var grammar = new GrammarAutoGenerated();
        var registry = new BeanRegistryImplementation(grammar);
        return GenericYamlParser.createAndPopulateNode(
                new ParsingContext<>("mcpProtection", registry, grammar, node, "$.mcpProtection", null),
                MCPProtectionInterceptor.class,
                node.get("mcpProtection")
        );
    }

    private String wrapConfig(String config) {
        if (config == null || config.isBlank()) {
            return "mcpProtection: {}\n";
        }
        return "mcpProtection:\n" + config.stripIndent().indent(2);
    }

    private Exchange exchange(String method, String contentType, String body) {
        Request.Builder builder = new Request.Builder()
                .method(method)
                .uri("/");
        if (contentType != null) {
            builder.contentType(contentType);
        }
        if (body != null) {
            builder.body(body);
        }
        return builder.buildExchange();
    }

    private void assertError(Exchange exc, int status, int code, String message, Object id) throws Exception {
        assertNotNull(exc.getResponse());
        assertEquals(status, exc.getResponse().getStatusCode());
        assertEquals(APPLICATION_JSON, exc.getResponse().getHeader().getContentType());

        JsonNode response = OM.readTree(exc.getResponse().getBodyAsStringDecoded());
        assertEquals("2.0", response.path("jsonrpc").asText());
        assertEquals(code, response.path("error").path("code").asInt());
        assertTrue(response.path("error").path("message").asText().contains(message));

        if (id == null) {
            assertTrue(response.path("id").isNull());
        } else {
            assertEquals(OM.valueToTree(id), response.path("id"));
        }
    }

    private record RequestCase(
            String name,
            String config,
            String httpMethod,
            String contentType,
            String body,
            Outcome expectedOutcome,
            Integer expectedStatus,
            Integer expectedCode,
            String expectedMessage,
            Object expectedId
    ) {
        @Override
        public String toString() {
            return name;
        }
    }

    @Test
    void suppressesJsonRpcErrorForRejectedNotification() throws Exception {
        var exc = exchange(METHOD_POST, APPLICATION_JSON, """
                {"jsonrpc":"2.0","method":"notifications/cancelled","params":{}}
                """);

        assertEquals(RETURN, interceptor("methods:\n  notifications: false").handleRequest(exc));
        assertNotNull(exc.getResponse());
        assertEquals(403, exc.getResponse().getStatusCode());
        assertTrue(exc.getResponse().getBodyAsStringDecoded().isEmpty());
    }

    @Test
    void sendsJsonRpcErrorForRejectedRequestWithNullId() throws Exception {
        var exc = exchange(METHOD_POST, APPLICATION_JSON, """
                {"jsonrpc":"2.0","id":null,"method":"resources/read","params":{}}
                """);

        assertEquals(RETURN, interceptor("").handleRequest(exc));
        assertError(
                exc,
                403,
                ERR_METHOD_NOT_FOUND,
                "MCP method 'resources/read' is not allowed.",
                null
        );
    }

    @Test
    void filtersDeniedToolsFromToolsListResponse() throws Exception {
        String config = """
                tools:
                  - allow: '^safe\\..*$'
                  - deny: '.*'
                """;

        var interceptor = interceptor(config);
        var exc = exchange(
                METHOD_POST,
                APPLICATION_JSON,
                """
                        {"jsonrpc":"2.0","id":21,"method":"tools/list","params":{}}
                        """
        );

        assertEquals(CONTINUE, interceptor.handleRequest(exc));
        exc.setResponse(Response.ok()
                .contentType(APPLICATION_JSON)
                .body("""
                        {
                          "jsonrpc": "2.0",
                          "id": 21,
                          "result": {
                            "tools": [
                              {"name": "safe.read"},
                              {"name": "hidden.delete"},
                              {"name": "public.info"}
                            ],
                            "nextCursor": "page-2",
                            "untouched": true
                          }
                        }
                        """)
                .build());

        assertEquals(CONTINUE, interceptor.handleResponse(exc));
        assertEquals(List.of("safe.read"), toolNames(exc));

        JsonNode response = OM.readTree(exc.getResponse().getBodyAsStringDecoded());
        assertEquals("page-2", response.path("result").path("nextCursor").asText());
        assertTrue(response.path("result").path("untouched").asBoolean());
    }

    @Test
    void hidesDeniedToolsFromToolsListResponseWhenUnmatchedToolsAreAllowedByDefault() throws Exception {
        String config = """
                tools:
                  - deny: '^private\\..*$'
                """;

        var interceptor = interceptor(config);
        var exc = toolsListExchange(23);

        assertEquals(CONTINUE, interceptor.handleRequest(exc));
        exc.setResponse(Response.ok()
                .contentType(APPLICATION_JSON)
                .body("""
                        {
                          "jsonrpc": "2.0",
                          "id": 23,
                          "result": {
                            "tools": [
                              {"name": "public.info"},
                              {"name": "private.delete"},
                              {"name": "unmatched.tool"}
                            ]
                          }
                        }
                        """)
                .build());

        assertEquals(CONTINUE, interceptor.handleResponse(exc));
        assertEquals(List.of("public.info", "unmatched.tool"), toolNames(exc));
    }

    @Test
    void hidesToolsDeniedByFirstMatchingRuleFromToolsListResponse() throws Exception {
        String config = """
                tools:
                  - deny: '^admin\\..*$'
                  - allow: '^admin\\.status$'
                  - allow: '^public\\..*$'
                """;

        var interceptor = interceptor(config);
        var exc = toolsListExchange(24);

        assertEquals(CONTINUE, interceptor.handleRequest(exc));
        exc.setResponse(Response.ok()
                .contentType(APPLICATION_JSON)
                .body("""
                        {
                          "jsonrpc": "2.0",
                          "id": 24,
                          "result": {
                            "tools": [
                              {"name": "admin.status"},
                              {"name": "admin.delete"},
                              {"name": "public.info"},
                              {"name": "unmatched.tool"}
                            ]
                          }
                        }
                        """)
                .build());

        assertEquals(CONTINUE, interceptor.handleResponse(exc));
        assertEquals(List.of("public.info", "unmatched.tool"), toolNames(exc));
    }

    @Test
    void leavesNonToolsListResponsesUnchanged() throws Exception {
        var interceptor = interceptor("tools:\n  - deny: '.*'");
        var exc = exchange(
                METHOD_POST,
                APPLICATION_JSON,
                """
                        {"jsonrpc":"2.0","id":22,"method":"ping","params":{}}
                        """
        );

        assertEquals(CONTINUE, interceptor.handleRequest(exc));
        String body = """
                {
                  "jsonrpc": "2.0",
                  "id": 22,
                  "result": {"tools": [{"name": "hidden.delete"}]}
                }
                """;
        exc.setResponse(Response.ok()
                .contentType(APPLICATION_JSON)
                .body(body)
                .build());

        assertEquals(CONTINUE, interceptor.handleResponse(exc));
        assertEquals(body, exc.getResponse().getBodyAsStringDecoded());
    }

    private Exchange toolsListExchange(int id) {
        return exchange(
                METHOD_POST,
                APPLICATION_JSON,
                """
                        {"jsonrpc":"2.0","id":%s,"method":"tools/list","params":{}}
                        """.formatted(id)
        );
    }

    private List<String> toolNames(Exchange exc) throws Exception {
        var names = new ArrayList<String>();
        OM.readTree(exc.getResponse().getBodyAsStringDecoded())
                .path("result")
                .path("tools")
                .forEach(tool -> names.add(tool.path("name").asText()));
        return names;
    }
}
