/* Copyright 2026 predic8 GmbH, www.predic8.com

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License. */

package com.predic8.membrane.core.interceptor.json.rpc;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;
import com.predic8.membrane.annot.beanregistry.BeanRegistryImplementation;
import com.predic8.membrane.annot.yaml.ParsingContext;
import com.predic8.membrane.annot.yaml.parsing.GenericYamlParser;
import com.predic8.membrane.core.config.spring.GrammarAutoGenerated;
import com.predic8.membrane.core.exchange.Exchange;
import com.predic8.membrane.core.http.Request;
import com.predic8.membrane.core.http.Response;
import com.predic8.membrane.core.interceptor.Outcome;
import com.predic8.membrane.core.router.DefaultRouter;
import com.predic8.membrane.core.util.ConfigurationException;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;

import java.util.Map;
import java.util.stream.Stream;

import static com.predic8.membrane.core.http.MimeType.APPLICATION_JSON;
import static com.predic8.membrane.core.http.MimeType.TEXT_PLAIN;
import static com.predic8.membrane.core.http.Request.METHOD_GET;
import static com.predic8.membrane.core.http.Request.METHOD_POST;
import static com.predic8.membrane.core.interceptor.Outcome.CONTINUE;
import static com.predic8.membrane.core.interceptor.Outcome.RETURN;
import static com.predic8.membrane.core.jsonrpc.JSONRPCResponse.ERR_INTERNAL_ERROR;
import static com.predic8.membrane.core.jsonrpc.JSONRPCResponse.ERR_INVALID_PARAMS;
import static com.predic8.membrane.core.jsonrpc.JSONRPCResponse.ERR_INVALID_REQUEST;
import static com.predic8.membrane.core.jsonrpc.JSONRPCResponse.ERR_METHOD_NOT_FOUND;
import static org.junit.jupiter.api.Assertions.*;

class JsonRPCProtectionInterceptorTest {

    private static final ObjectMapper OM = new ObjectMapper();
    private static final ObjectMapper YAML = new ObjectMapper(new YAMLFactory());

    private static final String PARAMS_LOCATION_CONFIG = """
            schemaValidation:
              methods:
                'rpc.echo':
                  params:
                    location: classpath:/json/rpc/echo-params.schema.json
            """;
    private static final String PARAMS_INLINE_CONFIG = """
            schemaValidation:
              methods:
                'rpc.inline':
                  params:
                    schema:
                      type: object
                      required:
                        - message
                      additionalProperties: false
                      properties:
                        message:
                          type: string
            """;
    private static final String RESPONSE_LOCATION_CONFIG = """
            schemaValidation:
              methods:
                'rpc.echo':
                  response:
                    location: classpath:/json/rpc/echo-result.schema.json
            """;
    private static final String RESPONSE_INLINE_CONFIG = """
            schemaValidation:
              methods:
                'rpc.inline':
                  response:
                    schema:
                      type: object
                      required:
                        - ok
                      additionalProperties: false
                      properties:
                        ok:
                          type: boolean
            """;
    private static final String BATCH_RESPONSE_CONFIG = """
            schemaValidation:
              methods:
                'rpc.echo':
                  response:
                    location: classpath:/json/rpc/echo-result.schema.json
                'rpc.health':
                  response:
                    location: classpath:/json/rpc/generic-rpc-params.schema.json
            """;
    private static final String ERROR_LOCATION_CONFIG = """
            schemaValidation:
              error:
                location: classpath:/json/rpc/error.schema.json
            """;
    private static final String ERROR_INLINE_CONFIG = """
            schemaValidation:
              error:
                schema:
                  type: object
                  required:
                    - code
                    - message
                    - data
                  properties:
                    code:
                      type: integer
                    message:
                      type: string
                    data:
                      type: object
                      required:
                        - reason
                      properties:
                        reason:
                          type: string
            """;

    @ParameterizedTest(name = "{0}")
    @MethodSource("requestCases")
    void validatesRequests(RequestCase testCase) throws Exception {
        var interceptor = interceptor(testCase.config());
        var exc = exchange(testCase.method(), testCase.contentType(), testCase.body());

        assertEquals(testCase.expectedOutcome(), interceptor.handleRequest(exc));

        if (testCase.expectsRejection()) {
            assertValidationError(
                    exc.getResponse(),
                    testCase.expectedStatus(),
                    testCase.expectedJsonRpcCode(),
                    testCase.expectedMessageSnippet(),
                    testCase.expectedId(),
                    testCase.batchErrorShape()
            );
            return;
        }

        assertNull(exc.getResponse());
    }

    @ParameterizedTest(name = "{0}")
    @MethodSource("responseCases")
    void validatesResponses(ResponseCase testCase) throws Exception {
        var interceptor = interceptor(testCase.config());
        var exc = exchange(METHOD_POST, APPLICATION_JSON, testCase.requestBody());

        if (testCase.requestBody() != null) {
            assertEquals(CONTINUE, interceptor.handleRequest(exc), "response test setup must pass request validation");
        }

        exc.setResponse(jsonResponse(testCase.responseBody()));
        assertEquals(testCase.expectedOutcome(), interceptor.handleResponse(exc));

        if (testCase.expectsRejection()) {
            assertValidationError(
                    exc.getResponse(),
                    testCase.expectedStatus(),
                    testCase.expectedJsonRpcCode(),
                    testCase.expectedMessageSnippet(),
                    testCase.expectedId(),
                    testCase.batchErrorShape()
            );
            return;
        }

        assertNotNull(exc.getResponse());
        assertTrue(exc.getResponse().getBodyAsStringDecoded().contains("\"jsonrpc\""));
    }

    @Test
    void parsesSchemaValidationConfigFromYaml() throws Exception {
        var interceptor = parseInterceptor("""
                schemaValidation:
                  error:
                    schema:
                      type: object
                      required:
                        - code
                      properties:
                        code:
                          type: integer
                  methods:
                    'rpc.echo':
                      params:
                        location: classpath:/json/rpc/echo-params.schema.json
                      response:
                        schema:
                          type: object
                          properties:
                            message:
                              type: string
                    'rpc.health':
                      response:
                        location: classpath:/json/rpc/generic-rpc-params.schema.json
                """);

        JsonRPCSchemaValidation schemaValidation = interceptor.getSchemaValidation();
        assertNotNull(schemaValidation);
        assertNotNull(schemaValidation.getErrorValidation());
        assertEquals(
                "object",
                schemaValidation.getErrorValidation().getSchema().getProperties().get("type")
        );

        Map<String, JsonRPCMethodSchemas> methods = schemaValidation.getMethods().getMethods();
        assertEquals(
                "classpath:/json/rpc/echo-params.schema.json",
                methods.get("rpc.echo").getParams().getLocation()
        );
        assertEquals(
                "string",
                ((Map<?, ?>) ((Map<?, ?>) methods.get("rpc.echo").getResponse().getSchema().getProperties().get("properties")).get("message")).get("type")
        );
        assertEquals(
                "classpath:/json/rpc/generic-rpc-params.schema.json",
                methods.get("rpc.health").getResponse().getLocation()
        );
    }

    @ParameterizedTest(name = "{0}")
    @MethodSource("invalidConfigCases")
    void rejectsInvalidConfigurations(InvalidConfigCase testCase) {
        RuntimeException exception = assertThrows(
                RuntimeException.class,
                () -> interceptor(testCase.config())
        );

        assertTrue(containsMessage(exception, testCase.expectedMessageSnippet()));
    }

    @Test
    void batchMaxSizeMustBePositive() {
        ConfigurationException exception = assertThrows(
                ConfigurationException.class,
                () -> new BatchRule().setMaxSize(0)
        );

        assertTrue(exception.getMessage().contains("batch maxSize must be greater than 0"));
    }

    private static Stream<RequestCase> requestCases() {
        return Stream.of(
                requestContinues(
                        "allow rule wins before later deny",
                        """
                                methods:
                                  - allow: '^rpc\\.health$'
                                  - deny: '^rpc\\..*$'
                                """,
                        """
                        {"jsonrpc":"2.0","id":1,"method":"rpc.health"}
                        """
                ),
                requestRejects(
                        "first matching deny rule rejects request",
                        """
                                methods:
                                  - deny: '^rpc\\..*$'
                                  - allow: '^rpc\\.health$'
                                """,
                        """
                        {"jsonrpc":"2.0","id":1,"method":"rpc.health"}
                        """,
                        403,
                        ERR_METHOD_NOT_FOUND,
                        "JSON-RPC method 'rpc.health' is not allowed.",
                        1
                ),
                requestContinues(
                        "non-POST requests are ignored",
                        "",
                        METHOD_GET,
                        TEXT_PLAIN,
                        "not-json"
                ),
                requestRejects(
                        "non-JSON content type is rejected",
                        "",
                        METHOD_POST,
                        TEXT_PLAIN,
                        """
                        {"jsonrpc":"2.0","id":1,"method":"rpc.health"}
                        """,
                        415,
                        ERR_INVALID_REQUEST,
                        "Content-Type text/plain is not supported. Expected application/json.",
                        null
                ),
                requestContinues(
                        "blank POST bodies are ignored",
                        "",
                        METHOD_POST,
                        APPLICATION_JSON,
                        "   "
                ),
                requestRejects(
                        "invalid JSON payload is rejected",
                        "",
                        "not-json",
                        400,
                        ERR_INVALID_REQUEST,
                        "Invalid JSON-RPC payload",
                        null
                ),
                requestRejects(
                        "payload must be an object or batch array",
                        "",
                        "1",
                        400,
                        ERR_INVALID_REQUEST,
                        "JSON-RPC payload must be an object or batch array.",
                        null
                ),
                requestRejects(
                        "method must be textual",
                        "",
                        """
                        {"jsonrpc":"2.0","id":1,"method":1}
                        """,
                        400,
                        ERR_INVALID_REQUEST,
                        "'method' must be a string",
                        null
                ),
                requestRejects(
                        "params must be an object or array",
                        "",
                        """
                        {"jsonrpc":"2.0","id":1,"method":"rpc.echo","params":1}
                        """,
                        400,
                        ERR_INVALID_REQUEST,
                        "'params' must be array or object",
                        null
                ),
                requestRejects(
                        "batch requests can be disabled",
                        """
                                batch:
                                  enabled: false
                                """,
                        """
                        [{"jsonrpc":"2.0","id":1,"method":"rpc.health"}]
                        """,
                        400,
                        ERR_INVALID_REQUEST,
                        "Batch requests are disabled.",
                        null
                ),
                requestRejects(
                        "batch size is limited",
                        """
                                batch:
                                  maxSize: 1
                                """,
                        """
                        [
                          {"jsonrpc":"2.0","id":1,"method":"rpc.one"},
                          {"jsonrpc":"2.0","id":2,"method":"rpc.two"}
                        ]
                        """,
                        400,
                        ERR_INVALID_REQUEST,
                        "Batch request exceeds maxSize of 1.",
                        null
                ),
                requestRejects(
                        "batch requests must not be empty",
                        "",
                        "[]",
                        400,
                        ERR_INVALID_REQUEST,
                        "Batch requests must not be empty.",
                        null
                ),
                requestRejects(
                        "every batch entry must be an object",
                        "",
                        """
                        [{"jsonrpc":"2.0","id":1,"method":"rpc.echo"},1]
                        """,
                        400,
                        ERR_INVALID_REQUEST,
                        "Each batch entry must be a JSON-RPC request object.",
                        null
                ),
                requestContinues(
                        "location-based params schema accepts matching payload",
                        PARAMS_LOCATION_CONFIG,
                        """
                        {"jsonrpc":"2.0","id":1,"method":"rpc.echo","params":{"message":"hello"}}
                        """
                ),
                requestRejects(
                        "location-based params schema rejects invalid payload",
                        PARAMS_LOCATION_CONFIG,
                        """
                        {"jsonrpc":"2.0","id":1,"method":"rpc.echo","params":{}}
                        """,
                        400,
                        ERR_INVALID_PARAMS,
                        "Invalid params for method 'rpc.echo'",
                        1
                ),
                requestContinues(
                        "inline params schema accepts matching payload",
                        PARAMS_INLINE_CONFIG,
                        """
                        {"jsonrpc":"2.0","id":1,"method":"rpc.inline","params":{"message":"hello"}}
                        """
                ),
                requestRejects(
                        "inline params schema rejects invalid payload",
                        PARAMS_INLINE_CONFIG,
                        """
                        {"jsonrpc":"2.0","id":1,"method":"rpc.inline","params":{}}
                        """,
                        400,
                        ERR_INVALID_PARAMS,
                        "Invalid params for method 'rpc.inline'",
                        1
                ),
                requestContinues(
                        "params validation uses exact method names",
                        PARAMS_LOCATION_CONFIG,
                        """
                        {"jsonrpc":"2.0","id":1,"method":"rpc.echo.v2","params":{}}
                        """
                ),
                requestRejects(
                        "notifications are rejected without a response id when a deny rule matches",
                        """
                                methods:
                                  - deny: '^rpc\\..*$'
                                  - allow: '^rpc\\.health$'
                                """,
                        """
                        {"jsonrpc":"2.0","method":"rpc.health"}
                        """,
                        403,
                        ERR_METHOD_NOT_FOUND,
                        "JSON-RPC method 'rpc.health' is not allowed.",
                        null
                )
        );
    }

    private static Stream<ResponseCase> responseCases() {
        return Stream.of(
                responseContinues(
                        "location-based response schema accepts matching result",
                        RESPONSE_LOCATION_CONFIG,
                        """
                        {"jsonrpc":"2.0","id":1,"method":"rpc.echo"}
                        """,
                        """
                        {"jsonrpc":"2.0","id":1,"result":{"message":"hello"}}
                        """
                ),
                responseRejects(
                        "location-based response schema rejects invalid result",
                        RESPONSE_LOCATION_CONFIG,
                        """
                        {"jsonrpc":"2.0","id":1,"method":"rpc.echo"}
                        """,
                        """
                        {"jsonrpc":"2.0","id":1,"result":{}}
                        """,
                        "Invalid result for method 'rpc.echo'",
                        1
                ),
                responseContinues(
                        "inline response schema accepts matching result",
                        RESPONSE_INLINE_CONFIG,
                        """
                        {"jsonrpc":"2.0","id":1,"method":"rpc.inline"}
                        """,
                        """
                        {"jsonrpc":"2.0","id":1,"result":{"ok":true}}
                        """
                ),
                responseRejects(
                        "inline response schema rejects invalid result",
                        RESPONSE_INLINE_CONFIG,
                        """
                        {"jsonrpc":"2.0","id":1,"method":"rpc.inline"}
                        """,
                        """
                        {"jsonrpc":"2.0","id":1,"result":{}}
                        """,
                        "Invalid result for method 'rpc.inline'",
                        1
                ),
                responseContinues(
                        "response validation uses exact method names",
                        RESPONSE_LOCATION_CONFIG,
                        """
                        {"jsonrpc":"2.0","id":1,"method":"rpc.echo.v2"}
                        """,
                        """
                        {"jsonrpc":"2.0","id":1,"result":{}}
                        """
                ),
                responseRejects(
                        "single responses must be objects",
                        RESPONSE_LOCATION_CONFIG,
                        """
                        {"jsonrpc":"2.0","id":1,"method":"rpc.echo"}
                        """,
                        "[]",
                        "JSON-RPC response must be an object.",
                        null
                ),
                responseRejects(
                        "unknown response ids are rejected",
                        RESPONSE_LOCATION_CONFIG,
                        """
                        {"jsonrpc":"2.0","id":1,"method":"rpc.echo"}
                        """,
                        """
                        {"jsonrpc":"2.0","id":9,"result":{"message":"hello"}}
                        """,
                        "JSON-RPC response id '9' does not match any request.",
                        9
                ),
                responseRejects(
                        "batch response validation resolves methods by request id",
                        BATCH_RESPONSE_CONFIG,
                        """
                        [
                          {"jsonrpc":"2.0","id":1,"method":"rpc.echo"},
                          {"jsonrpc":"2.0","id":2,"method":"rpc.health"}
                        ]
                        """,
                        """
                        [
                          {"jsonrpc":"2.0","id":2,"result":{"code":1}},
                          {"jsonrpc":"2.0","id":1,"result":{}}
                        ]
                        """,
                        "Invalid result for method 'rpc.echo'",
                        1
                ),
                responseRejects(
                        "batch responses must not be empty",
                        BATCH_RESPONSE_CONFIG,
                        """
                        [{"jsonrpc":"2.0","id":1,"method":"rpc.echo"}]
                        """,
                        "[]",
                        "Batch responses must not be empty.",
                        null
                ),
                responseRejects(
                        "every batch response entry must be an object",
                        BATCH_RESPONSE_CONFIG,
                        """
                        [{"jsonrpc":"2.0","id":1,"method":"rpc.echo"}]
                        """,
                        "[1]",
                        "Each batch entry must be a JSON-RPC response object.",
                        null
                ),
                responseContinues(
                        "notification responses are ignored when only success schemas are configured",
                        RESPONSE_LOCATION_CONFIG,
                        """
                        {"jsonrpc":"2.0","method":"rpc.echo"}
                        """,
                        """
                        {"jsonrpc":"2.0","id":1,"result":{}}
                        """
                ),
                responseContinues(
                        "notification responses are ignored when error and success schemas are configured",
                        ERROR_LOCATION_CONFIG + RESPONSE_LOCATION_CONFIG,
                        """
                        {"jsonrpc":"2.0","method":"rpc.echo"}
                        """,
                        """
                        {"jsonrpc":"2.0","id":1,"result":{"message":"hello"}}
                        """
                ),
                responseContinues(
                        "location-based error schema accepts matching error payload",
                        ERROR_LOCATION_CONFIG,
                        """
                        {"jsonrpc":"2.0","id":1,"method":"rpc.echo"}
                        """,
                        """
                        {"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"broken","data":{"reason":"timeout"}}}
                        """
                ),
                responseRejects(
                        "location-based error schema rejects invalid error payload",
                        ERROR_LOCATION_CONFIG,
                        """
                        {"jsonrpc":"2.0","id":1,"method":"rpc.echo"}
                        """,
                        """
                        {"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"broken"}}
                        """,
                        "Invalid error response",
                        1
                ),
                responseContinues(
                        "inline error schema accepts matching error payload",
                        ERROR_INLINE_CONFIG,
                        """
                        {"jsonrpc":"2.0","id":1,"method":"rpc.echo"}
                        """,
                        """
                        {"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"broken","data":{"reason":"timeout"}}}
                        """
                ),
                responseRejects(
                        "inline error schema rejects invalid error payload",
                        ERROR_INLINE_CONFIG,
                        """
                        {"jsonrpc":"2.0","id":1,"method":"rpc.echo"}
                        """,
                        """
                        {"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"broken"}}
                        """,
                        "Invalid error response",
                        1
                ),
                responseRejects(
                        "error validation also works without prior request context",
                        ERROR_INLINE_CONFIG,
                        null,
                        """
                        {"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"broken"}}
                        """,
                        "Invalid error response",
                        1
                )
        );
    }

    private static Stream<InvalidConfigCase> invalidConfigCases() {
        return Stream.of(
                invalidConfig(
                        "invalid regex patterns are rejected",
                        """
                        methods:
                          - allow: '[*'
                        """,
                        "Invalid regex pattern: [*"
                ),
                invalidConfig(
                        "schema definitions must not use location and inline schema together",
                        """
                        schemaValidation:
                          methods:
                            'rpc.echo':
                              params:
                                location: classpath:/json/rpc/echo-params.schema.json
                                schema:
                                  type: object
                        """,
                        "must define exactly one of 'location' or 'schema'"
                ),
                invalidConfig(
                        "inline schemas must not be empty",
                        """
                        schemaValidation:
                          methods:
                            'rpc.echo':
                              response:
                                schema: {}
                        """,
                        "must not be empty"
                ),
                invalidConfig(
                        "error schemas also require location or inline schema",
                        """
                        schemaValidation:
                          error: {}
                        """,
                        "must define exactly one of 'location' or 'schema'"
                )
        );
    }

    private static RequestCase requestContinues(String name, String config, String body) {
        return requestContinues(name, config, METHOD_POST, APPLICATION_JSON, body);
    }

    private static RequestCase requestContinues(String name, String config, String method, String contentType, String body) {
        return new RequestCase(name, config, method, contentType, body, CONTINUE, null, null, null, null, false);
    }

    private static RequestCase requestRejects(String name,
                                              String config,
                                              String body,
                                              int expectedStatus,
                                              int expectedJsonRpcCode,
                                              String expectedMessageSnippet,
                                              Object expectedId) {
        return requestRejects(name, config, METHOD_POST, APPLICATION_JSON, body, expectedStatus, expectedJsonRpcCode, expectedMessageSnippet, expectedId);
    }

    private static RequestCase requestRejects(String name,
                                              String config,
                                              String method,
                                              String contentType,
                                              String body,
                                              int expectedStatus,
                                              int expectedJsonRpcCode,
                                              String expectedMessageSnippet,
                                              Object expectedId) {
        return new RequestCase(
                name,
                config,
                method,
                contentType,
                body,
                RETURN,
                expectedStatus,
                expectedJsonRpcCode,
                expectedMessageSnippet,
                expectedId,
                payloadIsBatch(body)
        );
    }

    private static ResponseCase responseContinues(String name, String config, String requestBody, String responseBody) {
        return new ResponseCase(name, config, requestBody, responseBody, CONTINUE, null, null, null, null, false);
    }

    private static ResponseCase responseRejects(String name,
                                                String config,
                                                String requestBody,
                                                String responseBody,
                                                String expectedMessageSnippet,
                                                Object expectedId) {
        return new ResponseCase(
                name,
                config,
                requestBody,
                responseBody,
                RETURN,
                500,
                ERR_INTERNAL_ERROR,
                expectedMessageSnippet,
                expectedId,
                payloadIsBatch(requestBody != null ? requestBody : responseBody)
        );
    }

    private static InvalidConfigCase invalidConfig(String name, String config, String expectedMessageSnippet) {
        return new InvalidConfigCase(name, config, expectedMessageSnippet);
    }

    private JsonRPCProtectionInterceptor interceptor(String config) throws Exception {
        JsonRPCProtectionInterceptor interceptor = parseInterceptor(config);
        interceptor.init(new DefaultRouter());
        return interceptor;
    }

    private JsonRPCProtectionInterceptor parseInterceptor(String config) throws Exception {
        JsonNode node = YAML.readTree(wrapConfig(config));
        var grammar = new GrammarAutoGenerated();
        var registry = new BeanRegistryImplementation(grammar);
        return GenericYamlParser.createAndPopulateNode(
                new ParsingContext<>("jsonRPCProtection", registry, grammar, node, "$.jsonRPCProtection", null),
                JsonRPCProtectionInterceptor.class,
                node.get("jsonRPCProtection")
        );
    }

    private String wrapConfig(String config) {
        if (config == null || config.isBlank()) {
            return "jsonRPCProtection: {}\n";
        }
        return "jsonRPCProtection:\n" + config.stripIndent().indent(2);
    }

    private Exchange exchange(String method, String contentType, String body) {
        Request.Builder builder = new Request.Builder()
                .method(method)
                .uri("/");

        if (contentType != null) {
            builder.contentType(contentType);
        }
        if (body != null) {
            builder.body(body);
        }

        return builder.buildExchange();
    }

    private Response jsonResponse(String body) {
        return Response.ok()
                .json(body)
                .build();
    }

    private void assertValidationError(Response response,
                                       int expectedStatus,
                                       int expectedJsonRpcCode,
                                       String expectedMessageSnippet,
                                       Object expectedId,
                                       boolean batchShape) throws Exception {
        assertNotNull(response);
        assertEquals(expectedStatus, response.getStatusCode());

        JsonNode root = OM.readTree(response.getBodyAsStringDecoded());
        if (batchShape) {
            assertTrue(root.isArray());
            assertEquals(1, root.size());
            root = root.get(0);
        } else {
            assertTrue(root.isObject());
        }

        assertEquals("2.0", root.path("jsonrpc").asText());
        assertEquals(expectedJsonRpcCode, root.path("error").path("code").asInt());
        assertTrue(root.path("error").path("message").asText().contains(expectedMessageSnippet));

        JsonNode idNode = root.get("id");
        assertNotNull(idNode);
        if (expectedId == null) {
            assertTrue(idNode.isNull());
        } else {
            assertEquals(OM.valueToTree(expectedId), idNode);
        }
    }

    private static boolean payloadIsBatch(String payload) {
        return payload != null && payload.trim().startsWith("[");
    }

    private boolean containsMessage(Throwable throwable, String expectedMessageSnippet) {
        for (Throwable current = throwable; current != null; current = current.getCause()) {
            if (current.getMessage() != null && current.getMessage().contains(expectedMessageSnippet)) {
                return true;
            }
        }
        return false;
    }

    private record RequestCase(String name,
                               String config,
                               String method,
                               String contentType,
                               String body,
                               Outcome expectedOutcome,
                               Integer expectedStatus,
                               Integer expectedJsonRpcCode,
                               String expectedMessageSnippet,
                               Object expectedId,
                               boolean batchErrorShape) {
        private boolean expectsRejection() {
            return expectedOutcome == RETURN;
        }

        @Override
        public String toString() {
            return name;
        }
    }

    private record ResponseCase(String name,
                                String config,
                                String requestBody,
                                String responseBody,
                                Outcome expectedOutcome,
                                Integer expectedStatus,
                                Integer expectedJsonRpcCode,
                                String expectedMessageSnippet,
                                Object expectedId,
                                boolean batchErrorShape) {
        private boolean expectsRejection() {
            return expectedOutcome == RETURN;
        }

        @Override
        public String toString() {
            return name;
        }
    }

    private record InvalidConfigCase(String name, String config, String expectedMessageSnippet) {
        @Override
        public String toString() {
            return name;
        }
    }
}
