### Valid JSON - Should go through
POST http://localhost:2000
Content-Type: application/json

{
  "a": "av",
  "b": [
    2,
    "Tests",
    {
      "c": "cv"
    }
  ],
  "d": {
    "e": {
      "f": "fv"
    }
  }
}

### Exceeding maxTokens of 15
POST http://localhost:2000
Content-Type: application/json

{
  "a": {},
  "b": [
    2,
    "Tests",
    {
      "c": "cv"
    }
  ],
  "d": {
    "e": {
      "f": "fv"
    }
  }
}

### Document exceeding maxSize of 110
POST http://localhost:2000
Content-Type: application/json

{
  "a": "av",
  "b": [
    2,
    "Tests",
    {
      "c": "too"
    }
  ],
  "d": {
    "e": "many",
    "f": "chars"
  }
}

### Document with nesting exceeding maxDepth of 3
POST http://localhost:2000
Content-Type: application/json

{
  "a": {
    "b": {
      "c": {
        "d": "dv"
      }
    }
  }
}

### Document with string exceeding maxStringLength of 5
POST http://localhost:2000
Content-Type: application/json

{
  "a": "Exceeds max string length"
}

### Document with key exceeding maxKeyLength 1
POST http://localhost:2000
Content-Type: application/json

{
  "Key too long": "av"
}

### Document with object exceeding maxObjectSize of 3
POST http://localhost:2000
Content-Type: application/json

{
  "a": "av",
  "b": "bv",
  "c": "cv",
  "d": "dv"
}

### Document with array exceeding maxArraySize of 3
POST http://localhost:2000
Content-Type: application/json

{
  "a": [
    1,
    2,
    true,
    "Four"
  ]
}
