/* Copyright 2026 predic8 GmbH, www.predic8.com

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License. */

package com.predic8.membrane.examples;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.MappingIterator;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;
import com.networknt.schema.Error;
import com.networknt.schema.InputFormat;
import com.networknt.schema.Schema;
import com.networknt.schema.SchemaLocation;
import com.networknt.schema.SchemaRegistry;
import com.predic8.membrane.annot.beanregistry.BeanRegistryImplementation;
import com.predic8.membrane.annot.yaml.ParsingContext;
import com.predic8.membrane.annot.yaml.parsing.GenericYamlParser;
import com.predic8.membrane.core.config.spring.GrammarAutoGenerated;
import com.predic8.membrane.core.interceptor.lang.SetHeaderInterceptor;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;

import java.io.IOException;
import java.io.InputStream;
import java.io.Reader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import static com.networknt.schema.SpecificationVersion.DRAFT_2020_12;
import static java.nio.charset.StandardCharsets.UTF_8;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Every checked-in {@code *.apis.yaml} under {@code examples/} and {@code tutorials/} must
 * conform to Membrane's generated JSON schema.
 * <p>
 * Membrane's YAML parser is more permissive than the schema: for example
 * {@code ScalarValueConverter.coerceScalarOrReference} stringifies any scalar node - including a
 * bare YAML number or boolean - when the target setter expects a {@code String}. Such a value
 * parses and runs without complaint, even though the schema declares the attribute as
 * {@code "type": "string"} and would reject the very same value. This test catches that class of
 * dev mistake (an unquoted number/boolean where a string is expected) that the parser alone would
 * silently accept.
 */
class ApisYamlSchemaValidationTest {

    private static final ObjectMapper YAML = new ObjectMapper(new YAMLFactory());

    private static final String SCHEMA_CLASSPATH =
            "/com/predic8/membrane/core/config/json/membrane.schema.json";

    private static final Schema SCHEMA;

    static {
        try (InputStream in = ApisYamlSchemaValidationTest.class.getResourceAsStream(SCHEMA_CLASSPATH)) {
            if (in == null)
                throw new IOException("Schema not found on classpath: " + SCHEMA_CLASSPATH);
            SchemaRegistry registry = SchemaRegistry.withDefaultDialect(DRAFT_2020_12);
            SCHEMA = registry.getSchema(SchemaLocation.of(SCHEMA_CLASSPATH), in, InputFormat.JSON);
            SCHEMA.initializeValidators();
        } catch (Exception e) {
            throw new RuntimeException("Failed to load JSON schema", e);
        }
    }

    static Stream<String> getApisYamlConfigs() {
        List<String> roots = List.of("examples", "tutorials");
        return roots.stream()
                .map(Paths::get)
                .filter(Files::exists)
                .flatMap(root -> {
                    try (Stream<Path> paths = Files.walk(root)) {
                        return paths.filter(Files::isRegularFile)
                                .filter(p -> p.getFileName().toString().endsWith(".apis.yaml"))
                                .map(Path::toString)
                                .toList().stream();
                    } catch (IOException e) {
                        throw new RuntimeException(e);
                    }
                });
    }

    @ParameterizedTest
    @MethodSource("getApisYamlConfigs")
    void validateSchema(String yamlPath) throws Exception {
        try (Reader reader = Files.newBufferedReader(Paths.get(yamlPath), UTF_8)) {
            MappingIterator<JsonNode> it = YAML.readerFor(JsonNode.class).readValues(reader);

            while (it.hasNext()) {
                JsonNode doc = it.next();
                List<Error> errors = SCHEMA.validate(doc);
                assertTrue(errors.isEmpty(), "Schema validation failed for " + yamlPath + ":\n"
                        + errors.stream().map(Error::getMessage).collect(Collectors.joining("\n")));
            }
        }
    }

    /**
     * Demonstrates the exact dev mistake this class exists to catch: {@code setHeader}'s
     * {@code value} attribute is declared {@code "type": "string"} in the schema, but the YAML
     * parser coerces a bare (unquoted) number into a {@code String} without complaint, so the
     * config parses and runs fine while silently violating the schema.
     */
    @Test
    void bareNumberForStringAttributeParsesButViolatesSchema() throws Exception {
        JsonNode apiDoc = YAML.readTree("""
                api:
                  port: 2000
                  flow:
                    - setHeader:
                        name: X-Status
                        value: 200
                """);

        List<Error> errors = SCHEMA.validate(apiDoc);
        assertFalse(errors.isEmpty(), "schema should reject a number where \"value\" is declared as a string");
        assertTrue(errors.stream().anyMatch(e -> e.getInstanceLocation().toString().contains("value")),
                "expected the reported error to point at the \"value\" property, but got: "
                        + errors.stream().map(Error::getMessage).collect(Collectors.joining("\n")));

        JsonNode setHeaderNode = YAML.readTree("""
                setHeader:
                  name: X-Status
                  value: 200
                """);
        var grammar = new GrammarAutoGenerated();
        var registry = new BeanRegistryImplementation(grammar);
        SetHeaderInterceptor interceptor = GenericYamlParser.createAndPopulateNode(
                new ParsingContext<>("setHeader", registry, grammar, setHeaderNode, "$.setHeader", null),
                SetHeaderInterceptor.class,
                setHeaderNode.get("setHeader"));

        assertEquals("200", interceptor.getValue());
    }
}
