### Get access token
POST http://localhost:7007/oauth2/token
Content-Type: application/x-www-form-urlencoded

grant_type=password
    &username=john
    &password=password
    &client_id=abc
    &client_secret=def

# Execute the POST request above. You should be a response like that:
#
# {
#  "access_token": "5ta3kbi948eav3dtqs8vqus8j4",
#  "token_type": "Bearer",
#  "refresh_token": "6b6ll21lu7l0a8lasi9rvnstaq"
# }
#
# Copy the access_token and use it for the second request below

### Calling the resource.  using access token
GET http://localhost:2000
Authorization: Bearer <<Replace me with the access_token from the response of the first call>>
