/* Copyright 2026 predic8 GmbH, www.predic8.com

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License. */

package com.predic8.membrane.core.router;

import com.predic8.membrane.annot.beanregistry.BeanDefinition;
import com.predic8.membrane.annot.beanregistry.BeanDefinitionChanged;
import com.predic8.membrane.annot.beanregistry.BeanDefinitions;
import com.predic8.membrane.annot.beanregistry.BeanRegistryImplementation;
import com.predic8.membrane.core.config.spring.GrammarAutoGenerated;

import java.net.URI;
import java.net.URISyntaxException;
import java.nio.file.InvalidPathException;
import java.nio.file.Path;
import java.util.LinkedHashSet;
import java.util.List;

import static com.predic8.membrane.annot.yaml.WatchAction.ADDED;
import static com.predic8.membrane.core.util.OSUtil.isWindowsAbsolutePath;
import static com.predic8.membrane.core.util.URIUtil.pathFromFileURI;

/**
 * Parses YAML into a router instance and returns the local files that can later be watched for hot reloads.
 */
public final class YamlRouterBootstrap {

    private YamlRouterBootstrap() {
    }

    public static YamlConfigurationSource loadIntoRouter(DefaultRouter router, String location) throws Exception {
        var grammar = new GrammarAutoGenerated();
        var registry = new BeanRegistryImplementation(grammar);

        router.setRegistry(registry);
        registry.register("router", router);

        List<BeanDefinition> definitions = registry.parseYamlBeanDefinitions(
                router.getResolverMap().resolve(location),
                grammar,
                getRootSourceFile(location)
        );

        return loadDefinitionsIntoRouter(router, location, registry, definitions);
    }

    public static YamlConfigurationSource loadSnapshotIntoRouter(DefaultRouter router, YamlConfigurationSource source) {
        var grammar = new GrammarAutoGenerated();
        var registry = new BeanRegistryImplementation(grammar);

        router.setRegistry(registry);
        registry.register("router", router);

        for (BeanDefinition definition : source.definitionSnapshot()) {
            registry.handle(new BeanDefinitionChanged(ADDED, definition), false);
        }

        return loadDefinitionsIntoRouter(router, source.location(), registry, source.definitionSnapshot());
    }

    private static YamlConfigurationSource loadDefinitionsIntoRouter(DefaultRouter router, String location, BeanRegistryImplementation registry, List<BeanDefinition> definitions) {
        BeanDefinitions beanDefinitions = new BeanDefinitions(definitions);
        beanDefinitions.ensureSingleGlobalDefinition();
        beanDefinitions.getConfigDefinition().ifPresent(configBd -> router.applyConfiguration((Configuration) registry.resolve(configBd.getName())));

        registry.finishStaticConfiguration();
        router.getConfiguration().setBaseLocation(location);
        return new YamlConfigurationSource(location, collectTrackedFiles(location, definitions), definitions);
    }

    static List<Path> collectTrackedFiles(String location, List<BeanDefinition> definitions) {
        LinkedHashSet<Path> trackedFiles = new LinkedHashSet<>();

        Path rootSourceFile = getRootSourceFile(location);
        if (rootSourceFile != null) {
            trackedFiles.add(rootSourceFile.toAbsolutePath().normalize());
        }

        for (BeanDefinition definition : definitions) {
            if (definition.getSourceMetadata() == null || definition.getSourceMetadata().sourceFile() == null) {
                continue;
            }
            trackedFiles.add(definition.getSourceMetadata().sourceFile().toAbsolutePath().normalize());
        }

        return List.copyOf(trackedFiles);
    }

    static Path getRootSourceFile(String location) {
        if (!isWindowsAbsolutePath(location)) {
            try {
                URI uri = new URI(location);
                String scheme = uri.getScheme();
                if (scheme != null && !"file".equalsIgnoreCase(scheme))
                    return null;
            } catch (URISyntaxException ignored) {
            }
        }

        try {
            return Path.of(pathFromFileURI(location));
        } catch (InvalidPathException ignored) {
            return null;
        }
    }
}
