@password =password
@clientid =abc
@clientsecret =def
@username =john

### Get access token
# @name getAADToken
POST http://localhost:7007/oauth2/token
Content-Type: application/x-www-form-urlencoded

grant_type=password
    &username={{username}}
    &password={{password}}
    &client_id={{clientid}}
    &client_secret={{clientsecret}}

### Extract access token from getAADToken request
@token = {{getAADToken.response.body.access_token}}


### Authentication using access token
GET http://localhost:2000
Authorization: Bearer {{token}}
