/* Copyright 2022 predic8 GmbH, www.predic8.com

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License. */
package com.predic8.membrane.core.config.spring.k8s;

import com.fasterxml.jackson.databind.JsonNode;
import com.predic8.membrane.annot.Grammar;
import com.predic8.membrane.core.config.spring.GrammarAutoGenerated;
import tools.jackson.databind.JsonNode;
import com.predic8.membrane.annot.K8sHelperGenerator;
import com.predic8.membrane.core.config.spring.K8sHelperGeneratorAutoGenerated;
import com.predic8.membrane.annot.yaml.BeanRegistry;
import com.predic8.membrane.annot.yaml.GenericYamlParser;
import org.snakeyaml.engine.v2.events.Event;
import org.snakeyaml.engine.v2.events.MappingEndEvent;
import org.snakeyaml.engine.v2.events.MappingStartEvent;
import org.snakeyaml.engine.v2.events.ScalarEvent;

import java.util.*;

public class Envelope {
    String kind;
    String apiVersion;
    Metadata metadata;
    JsonNode spec;
    final Map<String, Object> additionalProperties = new HashMap<>();

    private static final Grammar K8S_HELPER = new GrammarAutoGenerated();

    public void parse(JsonNode node, BeanRegistry registry) {
        kind = node.get("kind").asText();
        apiVersion = node.get("apiVersion").asText();
        metadata = readMetadata(node.get("metadata"));
        spec = node.get("spec");
        //GenericYamlParser.parse(kind, clazz, events, registry, K8S_HELPER);
    }

    public static class Metadata {
        String name;
        String namespace;
        String uid;
        final Map<String,Object> additionalProperties = new TreeMap<>();

        public String getUid() {
            return uid;
        }
    }

    private Metadata readMetadata(JsonNode node) {
        Metadata metadata = new Metadata();
        metadata.name = node.get("name").asText();
        metadata.namespace = node.get("namespace").asText();
        metadata.uid = node.get("uid").asText();
        return metadata;
    }

    public Object getSpec() {
        return spec;
    }

    public Metadata getMetadata() {
        return metadata;
    }
}
