/* Copyright 2009, 2021 predic8 GmbH, www.predic8.com

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License. */
package com.predic8.membrane.core.kubernetes;

import com.fasterxml.jackson.databind.*;
import com.predic8.membrane.annot.yaml.*;
import com.predic8.membrane.core.*;
import com.predic8.membrane.core.config.spring.*;
import com.predic8.membrane.core.interceptor.kubernetes.*;
import com.predic8.membrane.core.kubernetes.client.*;
import com.predic8.membrane.core.proxies.*;
import org.slf4j.*;

import javax.annotation.*;
import java.io.*;
import java.util.*;
import java.util.concurrent.*;

/**
 * Creates watcher on all known CustomResourceDefinitions listed at {@link GrammarAutoGenerated}
 */
public class KubernetesWatcher {
    private static final Logger LOG = LoggerFactory.getLogger(KubernetesWatcher.class);

    private final Router router;
    private final BeanRegistryImplementation beanRegistry;
    private KubernetesClient client;
    private ExecutorService executors;
    private final ConcurrentHashMap<String, Closeable> watches = new ConcurrentHashMap<>();

    public KubernetesWatcher(Router router) {
        this.router = router;
        this.beanRegistry = new BeanRegistryImplementation(router, new GrammarAutoGenerated());
    }

    public void start() {
        Optional<KubernetesValidationInterceptor> kvi = findK8sValidatingInterceptor();
        if (kvi.isEmpty()) {
            return;
        }

        beanRegistry.start();

        client = getClient();

        List<String> crds = beanRegistry.getGrammar().getCrdSingularNames();
        if (kvi.get().getResourcesList().size() > 0)
            crds = crds.stream().filter(s -> kvi.get().getResourcesList().contains(s)).toList();
        if (crds.size() > 0)
            this.executors = Executors.newFixedThreadPool(crds.size());
        List<String> namespaces = new ArrayList<>(kvi.get().getNamespacesList());
        if (namespaces.size() == 1 && "*".equals(namespaces.get(0)))
            namespaces.set(0, null);
        crds.forEach(crd -> namespaces.forEach(ns -> createWatcher(ns, crd)));
    }

    public void stop() {
        watches.values().forEach(c -> {
            try {
                c.close();
            } catch (IOException e) {
            }
        });
    }

    private KubernetesClient getClient() {
        return router.getKubernetesClientFactory().createClient(null);
    }

    private Optional<KubernetesValidationInterceptor> findK8sValidatingInterceptor() {
        return router.getRules().stream()
                .map(Proxy::getFlow)
                .filter(Objects::nonNull)
                .flatMap(Collection::stream)
                .filter(inter -> inter instanceof KubernetesValidationInterceptor)
                .map(inter -> (KubernetesValidationInterceptor) inter)
                .findFirst();
    }

    private boolean isInK8sCluster() {
        return System.getenv("KUBERNETES_SERVICE_HOST") != null;
    }

    @SuppressWarnings("rawtypes")
    private void createWatcher(String namespace, String crd) {
        try {
            watches.put(namespace + "/" + crd, client.watch("membrane-api.io/v1beta2", crd, namespace, null, executors, new Watcher() {
                @Override
                public void onEvent(WatchAction action, JsonNode node) {
                    try {
                        System.err.println(action + " " + crd + " %s/%s".formatted(
                                node.get("metadata").get("namespace").asText(),
                                node.get("metadata").get("name").asText()));

                        beanRegistry.handle(action, node.get("spec"));
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }

                @Override
                public void onClosed(@Nullable Throwable t) {
                    LOG.error("Watcher for "+crd+" closed unexpectedly, restarting...", t);
                    createWatcher(namespace, crd);
                }
            }));
            LOG.debug("Added Watcher for {}", crd);
        } catch (IOException | KubernetesApiException e) {
            // TODO: retry in 1 min
            e.printStackTrace();
        }
    }

}
