/* Copyright 2025 predic8 GmbH, www.predic8.com

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License. */
package com.predic8.membrane.annot;

import com.predic8.membrane.annot.util.CompilerHelper;
import com.predic8.membrane.annot.util.CustomJavaFileManager;
import com.predic8.membrane.annot.util.InMemoryJavaFile;
import org.junit.jupiter.api.Test;

import javax.tools.*;
import java.net.URI;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class SpringConfigurationXSDGeneratingAnnotationProcessorTest {

    @Test
    public void simpleTest() {
        JavaFileObject sourceObject1 = new InMemoryJavaFile("com.predic8.membrane.demo.Demo", """
                package com.predic8.membrane.demo;
                import com.predic8.membrane.annot.MCMain;
                @MCMain(
                        outputPackage = "com.predic8.membrane.demo.config.spring",
                        outputName = "router-conf.xsd",
                        targetNamespace = "http://membrane-soa.org/demo/1/")
                public class Demo {
                }
                """);

        JavaFileObject sourceObject2 = new InMemoryJavaFile("com.predic8.membrane.demo.NamespaceHandler",
        """
                package com.predic8.membrane.demo.config.spring;
                import com.predic8.membrane.annot.AbstractNamespaceHandler;
                public class NamespaceHandler extends AbstractNamespaceHandler {
                	@Override
                	public void init() {
                		NamespaceHandlerAutoGenerated.registerBeanDefinitionParsers(this);
                	}
                }
                """);


        var result = CompilerHelper.run(List.of(sourceObject1, sourceObject2));

        assertEquals(0, result.diagnostics().getDiagnostics().size());
        assertTrue(result.compilationSuccess());
    }
}
