/* Copyright 2025 predic8 GmbH, www.predic8.com
   Licensed under the Apache License, Version 2.0 (the "License");
   http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License. */

package com.predic8.membrane.core.kubernetes;

import com.fasterxml.jackson.core.*;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.dataformat.yaml.*;
import com.predic8.membrane.annot.*;
import com.predic8.membrane.annot.beanregistry.*;
import com.predic8.membrane.annot.yaml.*;
import com.predic8.membrane.core.config.spring.*;
import com.predic8.membrane.core.interceptor.authentication.*;
import com.predic8.membrane.core.interceptor.authentication.session.*;
import com.predic8.membrane.core.interceptor.balancer.*;
import com.predic8.membrane.core.interceptor.beautifier.*;
import com.predic8.membrane.core.interceptor.flow.*;
import com.predic8.membrane.core.interceptor.lang.*;
import com.predic8.membrane.core.interceptor.log.*;
import com.predic8.membrane.core.interceptor.oauth2client.*;
import com.predic8.membrane.core.interceptor.ratelimit.*;
import com.predic8.membrane.core.interceptor.rewrite.*;
import com.predic8.membrane.core.interceptor.xml.*;
import com.predic8.membrane.core.openapi.serviceproxy.*;
import com.predic8.membrane.core.proxies.*;
import com.predic8.membrane.core.util.*;
import org.jetbrains.annotations.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.TestInstance.*;
import org.junit.jupiter.params.*;
import org.junit.jupiter.params.provider.*;

import java.io.*;
import java.lang.reflect.*;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static com.predic8.membrane.core.openapi.serviceproxy.OpenAPISpec.YesNoOpenAPIOption.*;
import static org.junit.jupiter.api.Assertions.*;

@TestInstance(Lifecycle.PER_CLASS)
public class GenericYamlParserTest {

    private static final ObjectMapper yamlMapper = new ObjectMapper(new YAMLFactory());

    private static final Grammar K8S_HELPER = new GrammarAutoGenerated();

    @ParameterizedTest
    @MethodSource("successCases")
    void parses_with_expectations(Case c) {
        c.check().accept(parse(c.yaml(), c.reg()));
    }

    @ParameterizedTest
    @MethodSource("errorCases")
    void fails_with_exception(ErrCase c) {
        assertThrows(c.expected(), () -> parse(c.yaml(), c.reg()));
    }

    Stream<Case> successCases() {

        // Registries for ref/injection rows
        MemcachedConnector mem = new MemcachedConnector() {{
            setHost("localhost");
            setPort(3000);
        }};
        TestBeanRegistry memReg = new TestBeanRegistry().with("mem", mem);

        Target target = new Target() {{
            setUrl("https://ref.example");
        }};
        TestBeanRegistry targetReg = new TestBeanRegistry().with("target", target);

        ResponseInterceptor responseInterceptor = new ResponseInterceptor();
        TestBeanRegistry responseReg = new TestBeanRegistry().with("response", responseInterceptor);

        return Stream.of(
                ok(
                        "port_parsed",
                        """
                        port: 2000
                        """,
                        a -> assertEquals(2000, a.getPort())
                ),
                ok(
                        "target_url_parsed",
                        """
                        target:
                          url: https://api.predic8.de
                        """,
                        a -> assertEquals("https://api.predic8.de", a.getTarget().getUrl())
                ),
                ok(
                        "path_value_parsed",
                        """
                        path:
                          uri: /names
                        """,
                        a -> assertEquals("/names", a.getPath().getUri())
                ),
                ok(
                        "interceptors_parsed",
                        """
                        flow:
                          - rateLimiter:
                              requestLimit: 3
                          - rewriter: []
                          - response: []
                        """,
                        a -> assertAll(
                                () -> assertEquals(3, a.getFlow().size()),
                                () -> assertInstanceOf(RateLimitInterceptor.class, a.getFlow().getFirst()),
                                () -> assertInstanceOf(RewriteInterceptor.class, a.getFlow().get(1)),
                                () -> assertInstanceOf(ResponseInterceptor.class, a.getFlow().get(2))
                        )
                ),
                ok(
                        "rateLimiter_requestLimit_parsed",
                        """
                        flow:
                          - rateLimiter:
                              requestLimit: 3
                              requestLimitDuration: PT30S
                        """,
                        a -> assertAll(
                                () -> assertEquals(3, ((RateLimitInterceptor) a.getFlow().getFirst()).getRequestLimit()),
                                () -> assertEquals("PT30S", ((RateLimitInterceptor) a.getFlow().getFirst()).getRequestLimitDuration())
                        )
                ),
                ok(
                        "rewriter_mapping",
                        """
                        flow:
                          - rewriter:
                            - map:
                                from: ^/names/(.*)
                                to: /restnames/name\\.groovy\\?name=$1
                        """,
                        a -> assertAll(
                                () -> assertEquals("^/names/(.*)", ((RewriteInterceptor) a.getFlow().getFirst()).getMappings().getFirst().getFrom()),
                                () -> assertEquals("/restnames/name\\.groovy\\?name=$1", ((RewriteInterceptor) a.getFlow().getFirst()).getMappings().getFirst().getTo())
                        )
                ),
                ok(
                        "response_interceptors_parsed",
                        """
                        flow:
                          - response:
                            - beautifier: {}
                            - xml2Json: {}
                            - log: {}
                        """,
                        a -> assertAll(
                                () -> assertEquals(3, ((ResponseInterceptor) a.getFlow().getFirst()).getFlow().size()),
                                () -> assertInstanceOf(BeautifierInterceptor.class, ((ResponseInterceptor) a.getFlow().getFirst()).getFlow().getFirst()),
                                () -> assertInstanceOf(Xml2JsonInterceptor.class, ((ResponseInterceptor) a.getFlow().getFirst()).getFlow().get(1)),
                                () -> assertInstanceOf(LogInterceptor.class, ((ResponseInterceptor) a.getFlow().getFirst()).getFlow().get(2))
                        )
                ),
                ok(
                        "balancer_sessionTimeout_parsed",
                        """
                        flow:
                          - balancer:
                              sessionTimeout: 10000
                        """,
                        a -> assertAll(
                                () ->assertInstanceOf(Long.class, ((LoadBalancingInterceptor) a.getFlow().getFirst()).getSessionTimeout()),
                                () -> assertEquals(10000L, ((LoadBalancingInterceptor) a.getFlow().getFirst()).getSessionTimeout())
                        )
                ),
                ok(
                        "setCookies_cookie_fields",
                        """
                        flow:
                          - setCookies:
                            - cookie:
                                name: foo
                                value: bar
                                secure: false
                        """,
                        a -> {
                            SetCookiesInterceptor.CookieDef c = ((SetCookiesInterceptor) a.getFlow().getFirst()).getCookies().getFirst();
                            assertEquals("foo", c.getName());
                            assertEquals("bar", c.getValue());
                            assertInstanceOf(Boolean.class, c.isSecure());
                            assertFalse(c.isSecure());
                        }
                ),
                ok(
                        "basicAuth_user_attributes_map",
                        """
                        flow:
                          - basicAuthentication:
                              staticUserDataProvider:
                                users:
                                  - user:
                                      username: foo
                                      password: bar
                                      "a1": "t1"
                                      "a2": "t2"
                        """,
                        a -> {
                            StaticUserDataProvider.User u = ((BasicAuthenticationInterceptor) a.getFlow().getFirst()).getUsers().getFirst();
                            assertInstanceOf(Map.class, u.getAttributes());
                            assertEquals(Map.of("a1","t1","a2","t2","password","bar","username","foo"), u.getAttributes());
                        }
                ),

                ok(
                        "oauth2_memcached_ref_injected",
                        """
                        flow:
                          - oauth2Resource2:
                              memcachedOriginalExchangeStore:
                                connector: mem
                              membrane:
                                src: https://localhost/oauth2/
                        """,
                        memReg,
                        a -> {
                            OAuth2Resource2Interceptor i = (OAuth2Resource2Interceptor) a.getFlow().getFirst();
                            MemcachedOriginalExchangeStore store = (MemcachedOriginalExchangeStore) i.getOriginalExchangeStore();
                            assertSame(mem, store.getConnector());
                        }
                ),
                ok(
                        "ref_top_level_target",
                        """
                        $ref: target
                        """,
                        targetReg,
                        a -> {
                            assertSame(target, a.getTarget());
                            assertEquals("https://ref.example", a.getTarget().getUrl());
                        }
                ),
                ok(
                        "ref_interceptor_response",
                        """
                        flow:
                          - $ref: response
                        """,
                        responseReg,
                        a -> {
                            assertEquals(1, a.getFlow().size());
                            assertSame(responseInterceptor, a.getFlow().getFirst());
                        }
                ),
                ok(
                        "openapi_spec_single",
                        """
                        openApis:
                          - openapi:
                              location: fruitshop-api.yml
                              validateRequests: "yes"
                        """,
                        a -> {
                            assertEquals(1, a.getSpecs().size());
                            assertEquals("fruitshop-api.yml", a.getSpecs().getFirst().getLocation());
                            assertEquals(YES, a.getSpecs().getFirst().getValidateRequests());
                        }
                ),
                ok(
                        "openapi_spec_multiple",
                        """
                        openApis:
                          - openapi:
                              location: a.yml
                              validateRequests: "no"
                          - openapi:
                              location: b.yml
                              validateRequests: "yes"
                        """,
                        a -> {
                            assertEquals(2, a.getSpecs().size());
                            assertEquals("a.yml", a.getSpecs().getFirst().getLocation());
                            assertEquals("b.yml", a.getSpecs().get(1).getLocation());
                            assertEquals(NO, a.getSpecs().get(0).getValidateRequests());
                            assertEquals(YES, a.getSpecs().get(1).getValidateRequests());
                        }
                )
        );
    }

    Stream<ErrCase> errorCases() {
        TestBeanRegistry empty = new TestBeanRegistry();
        return Stream.of(
                err(
                        "invalid_ref",
                        """
                        $ref: target
                        """,
                        empty, RuntimeException.class
                ),
                err(
                        "port_not_a_number",
                        """
                        port: not-a-number
                        """,
                        empty, RuntimeException.class
                )
        );
    }

    record Case(String testName, String yaml, TestBeanRegistry reg, java.util.function.Consumer<APIProxy> check) {
        @Override public @NotNull String toString() { return testName; }
    }

    record ErrCase(String testName, String yaml, TestBeanRegistry reg, Class<? extends Throwable> expected) {
        @Override public @NotNull String toString() { return testName; }
    }

    private static Case ok(String testName, String yaml, java.util.function.Consumer<APIProxy> check) {
        return new Case(testName, yaml, null, check);
    }
    private static Case ok(String testName, String yaml, TestBeanRegistry reg, java.util.function.Consumer<APIProxy> check) {
        return new Case(testName, yaml, reg, check);
    }

    private static ErrCase err(String testName, String yaml, TestBeanRegistry reg, Class<? extends Throwable> expected) {
        return new ErrCase(testName, yaml, reg, expected);
    }

    static class TestBeanRegistry implements BeanRegistry, BeanCollector, BeanLifecycleManager {
        private final Map<String, Object> refs = new HashMap<>();
        TestBeanRegistry with(String key, Object v) { refs.put(key, v); return this; }
        @Override public Object resolve(String ref) { return refs.get(ref); }

        @Override
        public List<Object> getBeans() {
            return List.of();
        }

        @Override
        public void parseYamls(InputStream yamls, Grammar grammar) throws IOException {
            BeanCollector.super.parseYamls(yamls, grammar);
        }

        @Override
        public void handle(ChangeEvent changeEvent, boolean isLast) {}

        @Override
        public void start() {}

        @Override
        public Grammar getGrammar() {
            return null;
        }

        @Override
        public <T> List<T> getBeans(Class<T> clazz) {
            return List.of();
        }

        @Override
        public <T> Optional<T> getBean(Class<T> clazz) {
            return Optional.empty();
        }

        @Override
        public <T> Optional<T> getBean(String beanName, Class<T> clazz) {
            return Optional.empty();
        }

        @Override
        public void register(String beanName, Object object) {}

        @Override
        public <T> T registerIfAbsent(Class<T> type, Supplier<T> supplier) {
            return type.cast(null);
        }

        @Override
        public void close() {}

        @Override
        public void addPreDestroyCallback(Object bean, Method method) {}
    }

    private static APIProxy parse(String yaml, TestBeanRegistry reg) {
        return GenericYamlParser.createAndPopulateNode(new ParsingContext<TestBeanRegistry>("api", reg, K8S_HELPER), APIProxy.class, parse(yaml));
    }

    public static JsonNode parse(String yaml) {
        try {
            return yamlMapper.readTree(yaml);
        } catch (JsonProcessingException e) {
            throw new RuntimeException(e);
        }
    }
}