/* Copyright 2026 predic8 GmbH, www.predic8.com

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License. */

package com.predic8.membrane.core.kubernetes;

import com.fasterxml.jackson.databind.JsonNode;
import com.predic8.membrane.annot.Grammar;
import com.predic8.membrane.annot.beanregistry.BeanDefinition;
import com.predic8.membrane.annot.yaml.ConfigurationParsingException;
import com.predic8.membrane.annot.yaml.GenericYamlParser;
import com.predic8.membrane.core.config.spring.GrammarAutoGenerated;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import static java.nio.file.Files.readString;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class GenericYamlParserIncludeListTest {

    private static final Grammar K8S_HELPER = new GrammarAutoGenerated();

    @TempDir
    Path tempDir;

    @Test
    void includes_files_and_directories_in_include_order() throws Exception {
        write("bundle/20-second.apis.yaml", """
                api:
                  port: 2020
                """);
        write("bundle/10-first.apis.yml", """
                api:
                  port: 2010
                """);
        write("bundle/ignored.yaml", """
                api:
                  port: 9999
                """);
        write("bundle/notes.txt", "not yaml");

        assertEquals(
                List.of(2001, 2010, 2020, 3001, 9000),
                extractPorts(parseDefinitions("""
                        include:
                          - %s
                          - %s
                          - %s
                        ---
                        api:
                          port: 9000
                        """.formatted(
                        yamlPath(write("includes/01-first.apis.yaml", """
                                api:
                                  port: 2001
                                """)),
                        yamlPath(tempDir.resolve("bundle")),
                        yamlPath(write("includes/99-last.apis.yml", """
                                api:
                                  port: 3001
                                """))
                )))
        );
    }

    @Test
    void resolves_relative_includes_from_including_file() throws Exception {
        write("shared/dependency.apis.yaml", """
                api:
                  port: 1050
                """);

        assertEquals(
                List.of(1050, 1100, 1200),
                extractPorts(parseDefinitions("""
                        include:
                          - %s
                        ---
                        api:
                          port: 1200
                        """.formatted(yamlPath(write("nested/middle.apis.yaml", """
                                include:
                                  - ../shared/dependency.apis.yaml
                                ---
                                api:
                                  port: 1100
                                """)))))
        );
    }

    @Test
    void resolves_relative_includes_from_root_file_path() throws Exception {
        write("root/includes/dependency.apis.yaml", """
                api:
                  port: 1250
                """);
        Path rootFile = write("root/apis.yaml", """
                include:
                  - includes/dependency.apis.yaml
                ---
                api:
                  port: 1300
                """);

        assertEquals(
                List.of(1250, 1300),
                extractPorts(parseDefinitions(readString(rootFile), rootFile))
        );
    }

    @Test
    void rejects_cyclic_include_chains() throws Exception {
        write("cycle/b.apis.yaml", """
                include:
                  - a.apis.yaml
                """);

        ConfigurationParsingException ex = assertThrows(
                ConfigurationParsingException.class, () -> parseDefinitions("""
                        include:
                          - %s
                        """.formatted(yamlPath(write("cycle/a.apis.yaml", """
                                include:
                                  - b.apis.yaml
                                """))))
        );

        assertTrue(ex.getMessage().contains("Cyclic include detected"), ex.getMessage());
        assertTrue(ex.getMessage().contains("a.apis.yaml"), ex.getMessage());
        assertTrue(ex.getMessage().contains("b.apis.yaml"), ex.getMessage());
    }

    @Test
    void rejects_duplicate_component_ids_across_includes() throws Exception {
        Path first = write("components/one.apis.yaml", """
                components:
                  auth:
                    basicAuthentication:
                      fileUserDataProvider:
                        htpasswdPath: /etc/one.htpasswd
                """);
        Path second = write("components/two.apis.yaml", """
                components:
                  auth:
                    basicAuthentication:
                      fileUserDataProvider:
                        htpasswdPath: /etc/two.htpasswd
                """);

        ConfigurationParsingException ex = assertThrows(
                ConfigurationParsingException.class, () -> parseDefinitions("""
                        include:
                          - %s
                          - %s
                        """.formatted(yamlPath(first), yamlPath(second)))
        );

        assertTrue(ex.getMessage().contains("Duplicate component id '#/components/auth'"), ex.getMessage());
    }

    @Test
    void sourceMetadata() throws Exception {
        Path nested = write("root/shared/nested.apis.yaml", """
                api:
                  port: 4100
                """);
        Path included = write("root/includes/middle.apis.yaml", """
                include:
                  - ../shared/nested.apis.yaml
                ---
                api:
                  port: 4200
                """);
        Path rootFile = write("root/apis.yaml", """
                include:
                  - includes/middle.apis.yaml
                ---
                api:
                  port: 4300
                """);

        List<BeanDefinition> definitions = parseDefinitions(readString(rootFile), rootFile);

        assertSourceMetadata(
                findByPort(definitions, 4100),
                nested.getParent(),
                nested,
                rootFile
        );
        assertSourceMetadata(
                findByPort(definitions, 4200),
                included.getParent(),
                included,
                rootFile
        );
        assertSourceMetadata(
                findByPort(definitions, 4300),
                rootFile.getParent(),
                rootFile,
                rootFile
        );
    }

    private List<BeanDefinition> parseDefinitions(String yaml) throws IOException {
        return new GenericYamlParser(K8S_HELPER, yaml, null).getBeanDefinitions();
    }

    private List<BeanDefinition> parseDefinitions(String yaml, Path rootSourceFile) throws IOException {
        return new GenericYamlParser(K8S_HELPER, yaml, rootSourceFile).getBeanDefinitions();
    }

    private List<Integer> extractPorts(List<BeanDefinition> definitions) {
        return definitions.stream()
                .map(this::extractPort)
                .toList();
    }

    private int extractPort(BeanDefinition definition) {
        JsonNode apiNode = definition.getNode().get("api");
        assertNotNull(apiNode, "Expected 'api' object in bean definition: " + definition);
        JsonNode portNode = apiNode.get("port");
        assertNotNull(portNode, "Expected 'port' inside api definition: " + definition);
        return portNode.asInt();
    }

    private BeanDefinition findByPort(List<BeanDefinition> definitions, int port) {
        return definitions.stream()
                .filter(definition -> extractPort(definition) == port)
                .findFirst()
                .orElseThrow(() -> new AssertionError("No bean definition with port " + port + " found."));
    }

    private void assertSourceMetadata(BeanDefinition definition, Path expectedBasePath, Path expectedSourceFile, Path expectedRootSourceFile) {
        assertNotNull(definition.getSourceMetadata(), "Expected source metadata to be present.");
        assertEquals(expectedBasePath.toAbsolutePath().normalize(), definition.getSourceMetadata().basePath());
        assertEquals(expectedSourceFile.toAbsolutePath().normalize(), definition.getSourceMetadata().sourceFile());
        assertEquals(expectedRootSourceFile.toAbsolutePath().normalize(), definition.getSourceMetadata().rootSourceFile());
    }

    private Path write(String relativePath, String content) throws IOException {
        Path file = tempDir.resolve(relativePath);
        Files.createDirectories(file.getParent());
        Files.writeString(file, content.stripIndent());
        return file;
    }

    private static String yamlPath(Path path) {
        return "'" + path.toAbsolutePath().normalize().toString().replace("'", "''") + "'";
    }
}
