### Access JWT Protected Resource
GET / HTTP/1.1
Host: localhost:2001
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Im1lbWJyYW5lIn0.eyJzdWIiOiJ1c2VyQGV4YW1wbGUuY29tIiwiYXVkIjoib3JkZXIiLCJzY29wZSI6ImV4ZWN1dGUiLCJpYXQiOjE3Njc4MDMwODYsImV4cCI6MjA3NTM4NzA4NiwibmJmIjoxNzY3ODAyOTY2fQ.V661gIICLKzg3cAZIhl1632X-H_jQZSfuUjbqqxfShSpJZSBwqMvRLGHTso107miBnnLweNYTMxOjBoPrC5QruDcXbz32RzdGD9rY6uy47ewDCw6W4fzsETjjxstqebYQJIKiR1mGKOi418kv5Vecw23TvtrezRf8bq1ElzljcKzOioYnrxq4fyT8V9uCFccqub5WqMt8DaddfJGMt_WTLmFu_MlU4UMDdghF8wFgFaqGg-J5gQRd-EevfNc1DIw1s-Pu4nEjAgpZ94a1dMX7IbmcrONLrbtjJzoouMeKc_hJyeW8XWsggmULbOOI5sz2T-PL-MgmtQMk8Ewx37QWQ
