# For IntelliJ Users: Make sure to highlight any line of the request you want to execute,
# as the play button will execute the highlighted request, not the request the button is next to.

### Will be detected as a JSON request.
POST / HTTP/2
Host: localhost:2000
Content-Type: application/json

{"foo":  "bar"}

###
POST / HTTP/2
Host: localhost:2000
Content-Type: application/x-yaml

foo:  bar

###
GET / HTTP/2
Host: localhost:2001
Content-Type: application/json

{"foo":  "bar"}

###
POST / HTTP/2
Host: localhost:2001
Content-Type: text/plain

foobar

###
GET / HTTP/2
Host: localhost:2003

###
GET /?param1=value1 HTTP/2
Host: localhost:2003

###
GET / HTTP/2
Host: localhost:2004
X-Test-Header: foo

###
GET / HTTP/2
Host: localhost:2000
X-Test-Header: foobar

###
POST / HTTP/2
Host: localhost:2000
Content-Type: application/json

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.