# yaml-language-server: $schema=https://www.membrane-api.io/v7.4.0.json
#
# Tutorial: WSDL to OpenAPI
#
# A SOAP web service described by a WSDL can be automatically transformed into an API.
# wsdl2openapi generates an OpenAPI from the WSDL and converts incoming JSON
# requests to SOAP, and SOAP responses back to JSON.
#
# 1.) Start Membrane
#    Linux/Mac:
#      ./membrane.sh -c 95-WSDL-to-OpenAPI.yaml
#    Windows:
#      membrane.cmd -c 95-WSDL-to-OpenAPI.yaml
#
# 2.) Look at the generated OpenAPI and the Swagger UI
#     http://localhost:2000/api-docs
#
# 3.) Call the API
#    curl -d '{"name":"Berlin"}' -H "Content-Type: application/json" http://localhost:2000/get-city
#
#    Body is transformed to SOAP and routed to the SOAP service. The address is taken from the WSDL:
#    <s:address location="http://localhost:2001/city-service"/>
#
# 4.) Look at the SOAP messages in the log

api:
  port: 2000
  flow:
    - wsdl2openapi:
        wsdl: cities.wsdl

---
api:
  port: 2001
  path:
    uri: /city-service
  flow:
    - beautifier: {}
    - log:
        label: "****** SOAP Message *******"
    - sampleSoapService: {}