scrape_configs:
  - job_name: 'MembraneMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:2000']
        labels:
          application: 'Membrane'