package com.predic8.membrane.core.http;

import com.predic8.membrane.core.Constants;
import com.predic8.membrane.core.util.HttpUtil;

public class ErrorResponse extends Response {

	public ErrorResponse(int statusCode, String statusMessage, String msg) {
		setStatusCode(statusCode);
		setStatusMessage(statusMessage);
		setBody(new Body(getErrorPage(msg)));
		setHeader(HttpUtil.createHeaders(MimeType.TEXT_HTML));
	}
	
	private String getErrorPage(String msg) {
		StringBuffer buf = new StringBuffer();
		buf.append("<html>");
		
			buf.append("<head>");
				buf.append("<title>");
					buf.append("Membrane Router: Error Report");
				buf.append("</title>");
			buf.append("</head>");
		
			buf.append("<body>");
			
				buf.append("<h1>");
					buf.append("Error Report");
				buf.append("</h1>");
					
				buf.append("<p>");
					buf.append("Message: ");
					buf.append(msg);
				buf.append("</p>");
						
				buf.append("<p>");
					buf.append("This message was generated by ");
					buf.append("<a href='http://membrane-soa.org/'>Membrane HTTP Router</a>");
					buf.append("Version ");
					buf.append(Constants.VERSION);
				buf.append("</p>");
				
			buf.append("</body>");
		buf.append("</html>");
		return buf.toString();
		
	}
}
