apiVersion: membrane-api.io/v1beta2
kind: api
metadata:
  name: fruitshop-demo
spec:
  port: 2000
  specs:
    - openapi:
        location: ../../conf/fruitshop-api.yml

---

apiVersion: membrane-api.io/v1beta2
kind: serviceProxy
metadata:
  name: admin-console
spec:
  port: 9000
  interceptors:
    - adminConsole: {}

---

apiVersion: membrane-api.io/v1beta2
kind: api
metadata:
  name: log
spec:
  port: 2000
  ssl:
    key:
      private:

  interceptors:
    - log:
        message: Header ${header}
  target:
    url: https://api.predic8.de
