{
 "title": "Membrane",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Requests per Minute",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(membrane_count{rule!=\"predic8_de_prometheus\"}[1m])) *60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Access",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(rule) (delta(membrane_count{rule!=\"predic8_de_prometheus\"}[$__interval])) > 0",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 8, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(rate(membrane_good_time{rule=~\".+\"}[1m])) by (rule)>0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "500 Status Codes",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "floor(delta(membrane_count{code=~\"5..\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status Codes",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(code) (delta(membrane_count{rule!=\"predic8_de_prometheus\"}[$__interval])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming Traffic",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(membrane_good_bytes_req_body[1m])) by (rule)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outgoing Traffic",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(membrane_good_bytes_res_body[1m])) by (rule)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}