package com.predic8.membrane.core.interceptor.lang;

import com.predic8.membrane.annot.*;
import com.predic8.membrane.core.exchange.*;
import com.predic8.membrane.core.interceptor.*;
import com.predic8.membrane.core.util.*;
import org.slf4j.*;

import static com.predic8.membrane.core.exceptions.ProblemDetails.*;
import static com.predic8.membrane.core.interceptor.Interceptor.Flow.*;
import static com.predic8.membrane.core.interceptor.Outcome.*;
import static com.predic8.membrane.core.interceptor.Outcome.ABORT;
import static java.nio.charset.StandardCharsets.*;

/**
 * setBody sets the content of the HTTP message body to the specified value. The value
 * can be a static string, or it can be dynamically generated by an expression.
 * Different languages such as SpEL, Groovy, XMLPath or JsonPath are supported.
 * setBody does not support conditional processing or loops. When you need these features,
 * resort to the template plugin instead.
 *
 * The content of the message body is set as UTF-8 encoded bytes. Set a corresponding content type header if necessary.
 */
@MCElement(name = "setBody")
public class SetBodyInterceptor extends AbstractExchangeExpressionInterceptor {

    private static final Logger log = LoggerFactory.getLogger(SetBodyInterceptor.class);

    @Override
    public Outcome handleRequest(Exchange exc) {
        return handleInternal(exc, REQUEST);
    }

    @Override
    public Outcome handleResponse(Exchange exc) {
        return handleInternal(exc, RESPONSE);
    }

    private Outcome handleInternal(Exchange exchange, Flow flow) {
        try {
            // The value is typically set from YAML there we can assume UTF-8
            exchange.getMessage(flow).setBodyContent(exchangeExpression.evaluate(exchange, flow, String.class).getBytes(UTF_8));
            return CONTINUE;
        } catch (Exception e) {
            var root = ExceptionUtil.getRootCause(e);
            var message = "While evaluating expression %s: %s".formatted(expression, root.getMessage());
            log.info(message);

            internal(getRouter().isProduction(), getDisplayName())
                    .title("Error evaluating expression!")
                    .internal("expression", expression)
                    .exception(root)
                    .stacktrace(false)
                    .buildAndSetResponse(exchange);
            return ABORT;
        }
    }

    /**
     * Sets the expression to be evaluated for modifying the HTTP message body.
     * The provided string value can represent a static text or a dynamic expression
     *
     * @param value expression or static string
     */
    @MCAttribute
    public void setValue(String value) {
        this.expression = value;
    }

    public String getValue() {
        return expression;
    }

    @Override
    public String getDisplayName() {
        return "setBody";
    }

    @Override
    public String getShortDescription() {
        return "Sets the content of the HTTP message body to the expression: %s.".formatted(expression);
    }
}
