/* Copyright 2025 predic8 GmbH, www.predic8.com

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License. */

package com.predic8.membrane.core.interceptor.lang;

import com.predic8.membrane.annot.*;
import com.predic8.membrane.core.exchange.*;
import com.predic8.membrane.core.http.*;
import com.predic8.membrane.core.interceptor.*;
import com.predic8.membrane.core.lang.*;
import com.predic8.membrane.core.util.*;
import com.predic8.membrane.core.util.uri.*;
import org.jetbrains.annotations.*;
import org.slf4j.*;

import java.util.function.*;

import static com.predic8.membrane.core.exceptions.ProblemDetails.*;
import static com.predic8.membrane.core.interceptor.Interceptor.Flow.*;
import static com.predic8.membrane.core.interceptor.Outcome.*;
import static com.predic8.membrane.core.interceptor.Outcome.ABORT;
import static com.predic8.membrane.core.util.uri.EscapingUtil.Escaping.NONE;
import static com.predic8.membrane.core.util.uri.EscapingUtil.getEscapingFunction;
import static java.nio.charset.StandardCharsets.*;

/**
 * @description sets the content of the HTTP message body to the specified value. The value
 * can be a static string, or it can be dynamically generated by an expression.
 * Different languages such as SpEL, Groovy, XMLPath or JsonPath are supported.
 * setBody does not support conditional processing or loops. When you need these features,
 * resort to the template plugin instead.
 * <p>
 * The content of the message body is set as UTF-8 encoded bytes. Set a corresponding content type header if necessary.
 * </p>
 */
@MCElement(name = "setBody")
public class SetBodyInterceptor extends AbstractExchangeExpressionInterceptor {

    private static final Logger log = LoggerFactory.getLogger(SetBodyInterceptor.class);

    protected String contentType;

    @Override
    public Outcome handleRequest(Exchange exc) {
        return handleInternal(exc, REQUEST);
    }

    @Override
    public Outcome handleResponse(Exchange exc) {
        return handleInternal(exc, RESPONSE);
    }

    private Outcome handleInternal(Exchange exchange, Flow flow) {
        var msg = exchange.getMessage(flow);
        try {
            // The value is typically set from YAML there we can assume UTF-8
            var result = exchangeExpression.evaluate(exchange, flow, String.class);
            if (result == null) {
                result = "null";
            }
            msg.setBodyContent(result.getBytes(UTF_8));

            if (contentType != null) {
                msg.getHeader().setContentType(contentType);
            }

            return CONTINUE;
        } catch (Exception e) {
            var root = ExceptionUtil.getRootCause(e);
            var message = "While evaluating expression %s: %s".formatted(expression, root.getMessage());
            log.info(message);

            internal(router.getConfiguration().isProduction(), getDisplayName())
                    .title("Error evaluating expression!")
                    .internal("expression", expression)
                    .exception(root)
                    .stacktrace(false)
                    .buildAndSetResponse(exchange);
            return ABORT;
        }
    }

    protected ExchangeExpression getExchangeExpression() {
        return TemplateExchangeExpression.newInstance(this, language, expression, router,
                getEscapingFunction(contentType).orElseGet(() -> {
            log.warn("Turning off escaping for 'setBody'. No escaping found for content type {}. To enable escaping set 'contentType' on setBody.", contentType);
            return getEscapingFunction(NONE);
        }));
    }

    /**
     * Sets the expression to be evaluated for modifying the HTTP message body.
     * The provided string value can represent a static text or a dynamic expression
     *
     * @param value expression or static string
     */
    @MCAttribute
    public void setValue(String value) {
        this.expression = value;
    }

    public String getValue() {
        return expression;
    }

    @Override
    public String getDisplayName() {
        return "setBody";
    }

    @Override
    public String getShortDescription() {
        return "Sets the content of the HTTP message body to the expression: %s.".formatted(expression);
    }

    /**
     * @description Content-Type of the generated body content.
     * @example application/json
     */
    @MCAttribute
    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    public String getContentType() {
        return contentType;
    }
}
