openapi: '3.0.2'
info:
  title: Security Demo API
  version: '1.0'

servers:
  - url: http://localhost:2000/security-api/v1/

paths:
  /:
    get:
      security:
        - apikey: []
      responses:
        200:
          description: OK

components:
  securitySchemes:
    apikey:
      type: apiKey
      name: X-Api-Keyz
      in: query