openapi: 3.1.0
info:
  title: Simple Parameters API
  version: "1.0.0"
servers:
  - url: http://localhost

paths:
  /foo:
    get:
      parameters:
        - name: bar
          in: query
          explode: true
          schema:
            type: array
            items:
              type: string
        - name: baz
          in: query
          explode: true
          schema:
            type: integer
      responses:
        "200":
          description: OK

