{
 "title": "Membrane OpenAPI Validation",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Validation Errors Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(membrane_openapi_validation) by (entity, entitytype, path)",
     "legendFormat": "{{entitytype}}: {{entity}} ({{path}})"
    }
   ]
  },
  {
   "title": "Errors by Validation Type",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum(membrane_openapi_validation) by (entitytype))",
     "legendFormat": "{{entitytype}}"
    }
   ]
  },
  {
   "title": "Errors by URI Template",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(membrane_openapi_validation) by (uritemplate)",
     "legendFormat": "{{uritemplate}}"
    }
   ]
  },
  {
   "title": "Detailed Error Log (Instant)",
   "type": "table",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 9 },
   "targets": [
    {
     "expr": "sum(membrane_openapi_validation) by (method, path, entity, jsonpointer, schematype)"
    }
   ]
  }
 ]
}