# yaml-language-server: $schema=https://www.membrane-api.io/v7.6.0.json
#
# Tutorial: OpenAPI
#
# 1.) Start Membrane:
#     Open a terminal in this folder and run:
#
#     with Docker:
#       ./run-docker.sh -c 10-OpenAPI.apis.yaml   (Linux/Mac)
#       run-docker.cmd -c 10-OpenAPI.apis.yaml    (Windows)
#     or with Java:
#       ./membrane.sh -c 10-OpenAPI.apis.yaml     (Linux/Mac)
#       membrane.cmd -c 10-OpenAPI.apis.yaml      (Windows)
#
# 2.) Open /api-docs in the browser:
#     http://localhost:2000/api-docs
#
# 3.) Click on 'Fruit Shop API' to open the Swagger UI.
#
# 4.) Try out the API in the Swagger UI.
#
# 5.) Call the APIs:
#     curl http://localhost:2000/shop/v2/products
#     curl http://localhost:2000/dlp/fields/city

api:
  port: 2000
  openapi:
    - location: https://api.predic8.de/api-docs/dlp-field-information-api-v1-0-0
    - location: ../../conf/openapi/fruitshop-v2-2-0.oas.yml
